const teams = [
	{
		teamName: "aldosivi",
		players: [
			{ number: "31", name: "L. Ingolotti", position: "goalkeeper" },
			{ number: "1", name: "L. Pocrnjic", position: "goalkeeper" },
			{ number: "35", name: "F. Assmann", position: "goalkeeper" },
			{ number: "6", name: "J. Schunke", position: "defender" },
			{ number: "2", name: "J. Carli", position: "defender" },
			{ number: "3", name: "M. López", position: "defender" },
			{ number: "19", name: "M. Miers", position: "defender" },
			{ number: "28", name: "F. Román", position: "defender" },
			{ number: "23", name: "L. Villalba", position: "defender" },
			{ number: "14", name: "F. Milo", position: "defender" },
			{ number: "21", name: "E. Iñiguez", position: "defender" },
			{ number: "25", name: "N. Yeri", position: "defender" },
			{ number: "5", name: "G. Gil Romero", position: "midfielder" },
			{ number: "27", name: "M. Villarreal", position: "midfielder" },
			{ number: "-", name: "G. Lodico", position: "midfielder" },
			{ number: "33", name: "L. Maciel", position: "midfielder" },
			{ number: "10", name: "F. Grahl", position: "midfielder" },
			{ number: "36", name: "J. Indacoechea", position: "midfielder" },
			{ number: "32", name: "P. Becker", position: "midfielder" },
			{ number: "18", name: "F. Perinciolo", position: "midfielder" },
			{ number: "42", name: "J. Zarate", position: "midfielder" },
			{ number: "41", name: "M. Panaro", position: "forward" },
			{ number: "8", name: "J. Iritier", position: "forward" },
			{ number: "-", name: "L. Guzmán", position: "forward" },
			{ number: "30", name: "F. Pérez", position: "forward" },
			{ number: "16", name: "J. Zacaría", position: "forward" },
			{ number: "20", name: "M. Braida", position: "forward" },
			{ number: "9", name: "R. Contreras", position: "forward" },
			{ number: "7", name: "F. Andrada", position: "forward" },
			{ number: "22", name: "L. Rinaldi", position: "forward" },
			{ number: "17", name: "L. Di Yorio", position: "forward" },
			{ number: "40", name: "F. Tobares", position: "forward" },
			{ number: "29", name: "U. Ramírez", position: "forward" },

		]
	},
	{
		teamName: "argentinos",
		players: [
			{ number: "12", name: "L. Chaves", position: "goalkeeper" },
			{ number: "1", name: "L. Finochietto", position: "goalkeeper" },
			{ number: "31", name: "M. Acosta", position: "goalkeeper" },
			{ number: "34", name: "N. Forastiero", position: "goalkeeper" },
			{ number: "13", name: "M. Centurión", position: "defender" },
			{ number: "16", name: "C. Quintana", position: "defender" },
			{ number: "6", name: "M. Caruzzo", position: "defender" },
			{ number: "2", name: "M. Torrén", position: "defender" },
			{ number: "29", name: "M. Di Cesare", position: "defender" },
			{ number: "24", name: "E. Gómez", position: "defender" },
			{ number: "4", name: "K. Mac Allister", position: "defender" },
			{ number: "15", name: "J. Sandoval", position: "defender" },
			{ number: "20", name: "F. Vera", position: "midfielder" },
			{ number: "-", name: "F. Moyano", position: "midfielder" },
			{ number: "26", name: "M. Romero", position: "midfielder" },
			{ number: "18", name: "D. Sosa", position: "midfielder" },
			{ number: "-", name: "J. Gómez", position: "midfielder" },
			{ number: "11", name: "T. Andrade", position: "midfielder" },
			{ number: "8", name: "I. Colman", position: "midfielder" },
			{ number: "-", name: "L. Paiva", position: "midfielder" },
			{ number: "21", name: "F. Mater", position: "midfielder" },
			{ number: "10", name: "G. Florentín", position: "midfielder" },
			{ number: "25", name: "M. Coronel", position: "midfielder" },
			{ number: "28", name: "N. Silva", position: "forward" },
			{ number: "-", name: "M. Pisano", position: "forward" },
			{ number: "-", name: "F. Metilli", position: "forward" },
			{ number: "-", name: "J. Cabrera", position: "forward" },
			{ number: "14", name: "D. Saggiomo", position: "forward" },
			{ number: "27", name: "G. Hauche", position: "forward" },
			{ number: "39", name: "G. Ávalos", position: "forward" },
			{ number: "19", name: "J. Pucheta", position: "forward" },

		]
	},
	{
		teamName: "arsenal",
		players: [
			{ number: "-", name: "N. Navarro", position: "goalkeeper" },
			{ number: "12", name: "A. Rivero", position: "goalkeeper" },
			{ number: "16", name: "I. Gariglio", position: "defender" },
			{ number: "22", name: "R. Balbuena", position: "defender" },
			{ number: "6", name: "G. Suso", position: "defender" },
			{ number: "14", name: "M. Carabajal", position: "defender" },
			{ number: "19", name: "L. Marchi", position: "defender" },
			{ number: "3", name: "E. Papa", position: "defender" },
			{ number: "18", name: "J. Navas", position: "defender" },
			{ number: "4", name: "M. Abreliano", position: "defender" },
			{ number: "15", name: "R. Luna", position: "midfielder" },
			{ number: "27", name: "F. Kruspzky", position: "midfielder" },
			{ number: "5", name: "E. Méndez", position: "midfielder" },
			{ number: "26", name: "R. Ramírez", position: "midfielder" },
			{ number: "8", name: "J. Soraire", position: "midfielder" },
			{ number: "24", name: "A. Antilef", position: "midfielder" },
			{ number: "21", name: "L. Picco", position: "midfielder" },
			{ number: "11", name: "N. Castro", position: "midfielder" },
			{ number: "10", name: "L. Necul", position: "midfielder" },
			{ number: "31", name: "Alan Ruiz", position: "midfielder" },
			{ number: "28", name: "M. Belloso", position: "forward" },
			{ number: "32", name: "B. Báez", position: "forward" },
			{ number: "9", name: "L. Albertengo", position: "forward" },
			{ number: "23", name: "F. Pons", position: "forward" },
			{ number: "7", name: "N. Miracco", position: "forward" },
			{ number: "20", name: "J. Candia", position: "forward" },

		]
	},
	{
		teamName: "atltucuman",
		players: [
			{ number: "12", name: "T. Marchiori", position: "goalkeeper" },
			{ number: "1", name: "C. Lucchetti", position: "goalkeeper" },
			{ number: "20", name: "F. Pizzicanella", position: "goalkeeper" },
			{ number: "24", name: "G. Ortiz", position: "defender" },
			{ number: "-", name: "S. Vergini", position: "defender" },
			{ number: "6", name: "M. Osores", position: "defender" },
			{ number: "3", name: "F. Monzón", position: "defender" },
			{ number: "30", name: "G. Risso Patrón", position: "defender" },
			{ number: "2", name: "M. Ortiz", position: "defender" },
			{ number: "4", name: "G. Toledo", position: "defender" },
			{ number: "14", name: "A. Lagos", position: "defender" },
			{ number: "7", name: "F. Mussis", position: "midfielder" },
			{ number: "5", name: "A. Bustos", position: "midfielder" },
			{ number: "21", name: "C. Erbes", position: "midfielder" },
			{ number: "16", name: "N. Laméndola", position: "midfielder" },
			{ number: "8", name: "G. Acosta", position: "midfielder" },
			{ number: "23", name: "R. Carrera", position: "midfielder" },
			{ number: "19", name: "N. Aguirre", position: "midfielder" },
			{ number: "12", name: "E. Rosales", position: "midfielder" },
			{ number: "10", name: "L. Heredia", position: "midfielder" },
			{ number: "28", name: "J. Romero", position: "forward" },
			{ number: "11", name: "M. Alustiza", position: "forward" },
			{ number: "26", name: "L. Melano", position: "forward" },
			{ number: "9", name: "A. Lotti", position: "forward" },
			{ number: "22", name: "J. Toledo", position: "forward" },
			{ number: "29", name: "K. Isa Luna", position: "forward" },
			{ number: "18", name: "R. Ruiz Rodriguez", position: "forward" },

		]
	},
	{
		teamName: "banfield",
		players: [
			{ number: "1", name: "I. Arboleda", position: "goalkeeper" },
			{ number: "27", name: "F. Altamirano", position: "goalkeeper" },
			{ number: "2", name: "A. Maldonado", position: "defender" },
			{ number: "6", name: "L. Lollo", position: "defender" },
			{ number: "19", name: "A. Sosa", position: "defender" },
			{ number: "14", name: "F. Quinteros", position: "defender" },
			{ number: "32", name: "E. Coronel", position: "defender" },
			{ number: "24", name: "L. Gómez", position: "defender" },
			{ number: "5", name: "N. Linares", position: "midfielder" },
			{ number: "21", name: "M. Payero", position: "midfielder" },
			{ number: "18", name: "G. Galoppo", position: "midfielder" },
			{ number: "25", name: "A. Cabrera", position: "midfielder" },
			{ number: "23", name: "J. Gutiérrez", position: "midfielder" },
			{ number: "28", name: "M. González", position: "midfielder" },
			{ number: "10", name: "J. Dátolo", position: "midfielder" },
			{ number: "11", name: "A. Urzi", position: "forward" },
			{ number: "17", name: "M. Cuero", position: "forward" },
			{ number: "22", name: "J. Álvarez", position: "forward" },
			{ number: "-", name: "C. Villagra", position: "forward" },
			{ number: "9", name: "A. Fontana", position: "forward" },
			{ number: "29", name: "L. Pons", position: "forward" },
			{ number: "31", name: "M. Asenjo", position: "forward" },
			{ number: "16", name: "J. Cruz", position: "forward" },

		]
	},
	{
		teamName: "boca",
		players: [
			{ number: "1", name: "E. Andrada", position: "goalkeeper" },
			{ number: "28", name: "M. Roffo", position: "goalkeeper" },
			{ number: "17", name: "A. Rossi", position: "goalkeeper" },
			{ number: "13", name: "J. García", position: "goalkeeper" },
			{ number: "6", name: "M. Rojo", position: "defender" },
			{ number: "2", name: "L. López", position: "defender" },
			{ number: "24", name: "C. Izquierdoz", position: "defender" },
			{ number: "20", name: "G. Ávila", position: "defender" },
			{ number: "5", name: "C. Zambrano", position: "defender" },
			{ number: "35", name: "R. Giampaoli", position: "defender" },
			{ number: "18", name: "F. Fabra", position: "defender" },
			{ number: "3", name: "E. Mas", position: "defender" },
			{ number: "37", name: "A. Sández", position: "defender" },
			{ number: "29", name: "L. Jara", position: "defender" },
			{ number: "4", name: "J. Buffarini", position: "defender" },
			{ number: "21", name: "J. Campuzano", position: "midfielder" },
			{ number: "23", name: "D. González", position: "midfielder" },
			{ number: "39", name: "I. Fernández", position: "midfielder" },
			{ number: "14", name: "N. Capaldo", position: "midfielder" },
			{ number: "25", name: "A. Almendra", position: "midfielder" },
			{ number: "33", name: "A. Varela", position: "midfielder" },
			{ number: "36", name: "C. Medina", position: "midfielder" },
			{ number: "8", name: "E. Cardona", position: "midfielder" },
			{ number: "32", name: "G. Maroni", position: "midfielder" },
			{ number: "16", name: "A. Molinas", position: "midfielder" },
			{ number: "-", name: "C. Pavón", position: "forward" },
			{ number: "22", name: "S. Villa", position: "forward" },
			{ number: "34", name: "A. Obando", position: "forward" },
			{ number: "12", name: "G. Gerzel", position: "forward" },
			{ number: "11", name: "E. Salvio", position: "forward" },
			{ number: "30", name: "E. Zeballos", position: "forward" },
			{ number: "26", name: "E. Roldán", position: "forward" },
			{ number: "19", name: "M. Zárate", position: "forward" },
			{ number: "10", name: "C. Tevez", position: "forward" },
			{ number: "9", name: "R. Ábila", position: "forward" },
			{ number: "27", name: "F. Soldano", position: "forward" },
			{ number: "38", name: "L. Vázquez", position: "forward" },

		]
	},
	{
		teamName: "cantralcdba",
		players: [
			{ number: "-", name: "A. Mehring", position: "goalkeeper" },
			{ number: "1", name: "A. Sánchez", position: "goalkeeper" },
			{ number: "13", name: "C. Taborda", position: "goalkeeper" },
			{ number: "15", name: "E. López", position: "goalkeeper" },
			{ number: "17", name: "L. Caffaratti", position: "goalkeeper" },
			{ number: "44", name: "A. Maciel", position: "defender" },
			{ number: "-", name: "D. Rentería", position: "defender" },
			{ number: "6", name: "F. Sbuttoni", position: "defender" },
			{ number: "2", name: "F. Andueza", position: "defender" },
			{ number: "4", name: "O. Salomón", position: "defender" },
			{ number: "19", name: "M. Acuña", position: "defender" },
			{ number: "12", name: "J. Bay", position: "defender" },
			{ number: "3", name: "N. Banegas", position: "defender" },
			{ number: "-", name: "G. Bettini", position: "defender" },
			{ number: "-", name: "J. González", position: "defender" },
			{ number: "26", name: "C. Díaz", position: "defender" },
			{ number: "24", name: "H. Vera Oviedo", position: "defender" },
			{ number: "29", name: "I. Quílez", position: "defender" },
			{ number: "40", name: "A. Pinto", position: "midfielder" },
			{ number: "5", name: "C. Vega", position: "midfielder" },
			{ number: "14", name: "J. Galeano", position: "midfielder" },
			{ number: "39", name: "M. Montenegro", position: "midfielder" },
			{ number: "16", name: "A. Rojas", position: "midfielder" },
			{ number: "11", name: "J. Fernández", position: "midfielder" },
			{ number: "18", name: "F. Cerro", position: "midfielder" },
			{ number: "7", name: "M. Barraza", position: "midfielder" },
			{ number: "20", name: "N. Barrios", position: "forward" },
			{ number: "30", name: "S. Rosales", position: "forward" },
			{ number: "-", name: "C. Lattanzio", position: "forward" },
			{ number: "31", name: "M. Pato", position: "forward" },
			{ number: "10", name: "L. Vella", position: "forward" },
			{ number: "21", name: "L. Brochero", position: "forward" },
			{ number: "23", name: "S. Ribas", position: "forward" },
			{ number: "9", name: "C. Riaño", position: "forward" },
			{ number: "8", name: "J. Pereira", position: "forward" },
			{ number: "28", name: "A. Argañaraz", position: "forward" },

		]
	},
	{
		teamName: "colon",
		players: [
			{ number: "1", name: "L. Burián", position: "goalkeeper" },
			{ number: "17", name: "I. Chicco", position: "goalkeeper" },
			{ number: "22", name: "J. Hass", position: "goalkeeper" },
			{ number: "-", name: "P. Goltz", position: "defender" },
			{ number: "2", name: "B. Bianchi", position: "defender" },
			{ number: "3", name: "G. Piovi", position: "defender" },
			{ number: "-", name: "L. Acevedo", position: "defender" },
			{ number: "33", name: "F. Garcés", position: "defender" },
			{ number: "36", name: "G. Nardelli", position: "defender" },
			{ number: "31", name: "G. Escobar", position: "defender" },
			{ number: "-", name: "R. Delgado", position: "defender" },
			{ number: "58", name: "C. Ibarra", position: "defender" },
			{ number: "13", name: "Alex Vigo", position: "defender" },
			{ number: "21", name: "Eric Meza", position: "defender" },
			{ number: "14", name: "F. Lértora", position: "midfielder" },
			{ number: "8", name: "Y. Góez", position: "midfielder" },
			{ number: "34", name: "S. Moreyra", position: "midfielder" },
			{ number: "29", name: "R. Aliendro", position: "midfielder" },
			{ number: "-", name: "A. Castro", position: "midfielder" },
			{ number: "30", name: "S. Pierotti", position: "midfielder" },
			{ number: "7", name: "B. Farioli", position: "midfielder" },
			{ number: "35", name: "F. Farias", position: "midfielder" },
			{ number: "23", name: "C. Bernardi", position: "forward" },
			{ number: "10", name: "L. Rodríguez", position: "forward" },
			{ number: "38", name: "B. Fernández", position: "forward" },
			{ number: "32", name: "T. Sandoval", position: "forward" },
			{ number: "19", name: "W. Morelo", position: "forward" },

		]
	},
	{
		teamName: "defyjusticia",
		players: [
			{ number: "22", name: "E. Unsain", position: "goalkeeper" },
			{ number: "1", name: "M. Ledesma", position: "goalkeeper" },
			{ number: "-", name: "D. Rodríguez", position: "goalkeeper" },
			{ number: "21", name: "H. Martínez", position: "defender" },
			{ number: "28", name: "J. Rodríguez", position: "defender" },
			{ number: "2", name: "A. Frías", position: "defender" },
			{ number: "6", name: "F. Paredes", position: "defender" },
			{ number: "4", name: "A. Sienra", position: "defender" },
			{ number: "13", name: "R. Herrera", position: "defender" },
			{ number: "37", name: "E. Brítez", position: "defender" },
			{ number: "33", name: "N. Gallardo", position: "defender" },
			{ number: "24", name: "M. Duarte", position: "defender" },
			{ number: "3", name: "M. Benítez", position: "defender" },
			{ number: "-", name: "N. Tripichio", position: "defender" },
			{ number: "25", name: "N. Breitenbruch", position: "defender" },
			{ number: "14", name: "P. Ramírez", position: "defender" },
			{ number: "40", name: "F. Echevarria", position: "midfielder" },
			{ number: "30", name: "R. Loaiza", position: "midfielder" },
			{ number: "34", name: "E. Fernández", position: "midfielder" },
			{ number: "16", name: "L. Escalante", position: "midfielder" },
			{ number: "35", name: "V. Larralde", position: "midfielder" },
			{ number: "-", name: "T. Martínez", position: "midfielder" },
			{ number: "8", name: "J. Farías", position: "midfielder" },
			{ number: "10", name: "T. Ortiz", position: "midfielder" },
			{ number: "32", name: "M. Luayza", position: "midfielder" },
			{ number: "23", name: "E. Isnaldo", position: "forward" },
			{ number: "29", name: "F. Pizzini", position: "forward" },
			{ number: "31", name: "B. Romero", position: "forward" },
			{ number: "12", name: "Ciro Rius", position: "forward" },
			{ number: "-", name: "F. Bordagaray", position: "forward" },
			{ number: "27", name: "E. Coacci", position: "forward" },
			{ number: "7", name: "J. González", position: "forward" },
			{ number: "20", name: "W. Bou", position: "forward" },
			{ number: "15", name: "N. Leguizamón", position: "forward" },
			{ number: "19", name: "G. Hachen", position: "forward" },
			{ number: "9", name: "M. Merentiel", position: "forward" },

		]
	},
	{
		teamName: "estudiantes",
		players: [
			{ number: "21", name: "M. Andújar", position: "goalkeeper" },
			{ number: "1", name: "J. Pourtau", position: "goalkeeper" },
			{ number: "12", name: "E. González", position: "goalkeeper" },
			{ number: "26", name: "F. Tobio", position: "defender" },
			{ number: "-", name: "F. Noguera", position: "defender" },
			{ number: "6", name: "N. Colombo", position: "defender" },
			{ number: "17", name: "M. Guzmán", position: "defender" },
			{ number: "29", name: "L. Squadrone", position: "defender" },
			{ number: "22", name: "F. Mura", position: "defender" },
			{ number: "15", name: "N. Pasquini", position: "defender" },
			{ number: "3", name: "I. Erquiaga", position: "defender" },
			{ number: "4", name: "L. Godoy", position: "defender" },
			{ number: "5", name: "I. Gómez", position: "midfielder" },
			{ number: "-", name: "J. Rodríguez", position: "midfielder" },
			{ number: "24", name: "D. Ayala", position: "midfielder" },
			{ number: "25", name: "A. Ayala", position: "midfielder" },
			{ number: "31", name: "F. Romero", position: "midfielder" },
			{ number: "34", name: "B. Kociubinski", position: "midfielder" },
			{ number: "23", name: "E. Kalinski", position: "midfielder" },
			{ number: "-", name: "M. Castro", position: "midfielder" },
			{ number: "20", name: "D. García", position: "midfielder" },
			{ number: "10", name: "M. Díaz", position: "midfielder" },
			{ number: "28", name: "E. Obregón", position: "midfielder" },
			{ number: "19", name: "L. Rodríguez", position: "forward" },
			{ number: "8", name: "Á. González", position: "forward" },
			{ number: "16", name: "D. Sarmiento", position: "forward" },
			{ number: "18", name: "L. Díaz", position: "forward" },
			{ number: "7", name: "M. Cauteruccio", position: "forward" },
			{ number: "9", name: "F. González", position: "forward" },
			{ number: "-", name: "F. Apaolaza", position: "forward" },
			{ number: "33", name: "G. Di Pizio", position: "forward" },

		]
	},
	{
		teamName: "gimnasia",
		players: [
			{ number: "19", name: "J. Broun", position: "goalkeeper" },
			{ number: "1", name: "T. Durso", position: "goalkeeper" },
			{ number: "12", name: "N. Insfrán", position: "goalkeeper" },
			{ number: "24", name: "G. Guiffrey", position: "defender" },
			{ number: "23", name: "M. Coronel", position: "defender" },
			{ number: "38", name: "T. Fernández", position: "defender" },
			{ number: "32", name: "M. Melluso", position: "defender" },
			{ number: "25", name: "L. Licht", position: "defender" },
			{ number: "57", name: "M. Weigandt", position: "defender" },
			{ number: "4", name: "L. Morales", position: "defender" },
			{ number: "5", name: "H. Mancilla", position: "midfielder" },
			{ number: "16", name: "V. Ayala", position: "midfielder" },
			{ number: "26", name: "J. Paradela", position: "midfielder" },
			{ number: "22", name: "M. Miranda", position: "midfielder" },
			{ number: "15", name: "B. Alemán", position: "midfielder" },
			{ number: "31", name: "M. Pérez García", position: "midfielder" },
			{ number: "21", name: "L. Chávez", position: "midfielder" },
			{ number: "34", name: "P. Monti", position: "midfielder" },
			{ number: "-", name: "H. Tijanovich", position: "forward" },
			{ number: "-", name: "M. Gómez", position: "forward" },
			{ number: "7", name: "J. Carbonero", position: "forward" },
			{ number: "43", name: "E. Ramírez", position: "forward" },
			{ number: "-", name: "M. Comba", position: "forward" },
			{ number: "9", name: "N. Contin", position: "forward" },
			{ number: "18", name: "L. Barrios", position: "forward" },
			{ number: "37", name: "S. Cocimano", position: "forward" },

		]
	},
	{
		teamName: "godoycruz",
		players: [
			{ number: "1", name: "R. Ramírez", position: "goalkeeper" },
			{ number: "-", name: "J. Espínola", position: "goalkeeper" },
			{ number: "25", name: "J. Bolado", position: "goalkeeper" },
			{ number: "23", name: "N. Ibáñez", position: "goalkeeper" },
			{ number: "22", name: "G. Ferrari", position: "defender" },
			{ number: "2", name: "G. Goñi", position: "defender" },
			{ number: "-", name: "B. Alférez", position: "defender" },
			{ number: "24", name: "Z. Romero", position: "defender" },
			{ number: "-", name: "A. Aleo", position: "defender" },
			{ number: "26", name: "D. Pérez", position: "defender" },
			{ number: "3", name: "L. González", position: "defender" },
			{ number: "6", name: "I. Escobar", position: "defender" },
			{ number: "29", name: "H. Silva", position: "defender" },
			{ number: "15", name: "M. González", position: "midfielder" },
			{ number: "5", name: "W. Cartagena", position: "midfielder" },
			{ number: "30", name: "J. Andrada", position: "midfielder" },
			{ number: "31", name: "A. Álvarez", position: "midfielder" },
			{ number: "32", name: "G. Abrego", position: "midfielder" },
			{ number: "34", name: "L. Pizarro", position: "midfielder" },
			{ number: "11", name: "J. Elías", position: "midfielder" },
			{ number: "16", name: "A. Manzur", position: "midfielder" },
			{ number: "19", name: "F. Henríquez", position: "midfielder" },
			{ number: "28", name: "R. Tesuri", position: "midfielder" },
			{ number: "10", name: "V. Burgoa", position: "midfielder" },
			{ number: "17", name: "M. Ojeda", position: "forward" },
			{ number: "7", name: "V. Ramis", position: "forward" },
			{ number: "33", name: "E. Bullaude", position: "forward" },
			{ number: "20", name: "A. Cantero", position: "forward" },
			{ number: "9", name: "T. Badaloni", position: "forward" },
			{ number: "27", name: "S. Lomónaco", position: "forward" },

		]
	},
	{
		teamName: "huracan",
		players: [
			{ number: "1", name: "F. Cambeses", position: "goalkeeper" },
			{ number: "22", name: "J. Mendive", position: "goalkeeper" },
			{ number: "27", name: "R. Ferrario", position: "goalkeeper" },
			{ number: "32", name: "S. Meza", position: "goalkeeper" },
			{ number: "23", name: "L. Merolla", position: "defender" },
			{ number: "2", name: "R. Civelli", position: "defender" },
			{ number: "13", name: "W. Pérez", position: "defender" },
			{ number: "25", name: "C. Ibáñez", position: "defender" },
			{ number: "3", name: "L. Grimi", position: "defender" },
			{ number: "26", name: "E. Bonifacio", position: "defender" },
			{ number: "4", name: "R. Lozano", position: "defender" },
			{ number: "8", name: "A. Arregui", position: "midfielder" },
			{ number: "21", name: "E. Rolón", position: "midfielder" },
			{ number: "30", name: "D. Mercado", position: "midfielder" },
			{ number: "15", name: "F. Marín", position: "midfielder" },
			{ number: "11", name: "F. Cristaldo", position: "midfielder" },
			{ number: "5", name: "S. Hezze", position: "midfielder" },
			{ number: "14", name: "E. Navarro", position: "midfielder" },
			{ number: "42", name: "Pablo Oro", position: "midfielder" },
			{ number: "18", name: "P. Toranzo", position: "midfielder" },
			{ number: "7", name: "J. Garro", position: "forward" },
			{ number: "43", name: "A. Curruhinca", position: "forward" },
			{ number: "16", name: "B. Maidana", position: "forward" },
			{ number: "10", name: "Norberto Briasco", position: "forward" },
			{ number: "12", name: "S. Ramírez", position: "forward" },
			{ number: "39", name: "R. Cabral", position: "forward" },
			{ number: "17", name: "C. Núñez", position: "forward" },
			{ number: "9", name: "A. Chávez", position: "forward" },
			{ number: "24", name: "F. Coniglio", position: "forward" },
			{ number: "29", name: "D. Mendoza", position: "forward" },
			{ number: "19", name: "N. Cordero", position: "forward" },

		]
	},
	{
		teamName: "independiente",
		players: [
			{ number: "1", name: "S. Sosa", position: "goalkeeper" },
			{ number: "12", name: "R. Bacchia", position: "goalkeeper" },
			{ number: "13", name: "M. Álvarez", position: "goalkeeper" },
			{ number: "2", name: "A. Franco", position: "defender" },
			{ number: "26", name: "A. Barboza", position: "defender" },
			{ number: "6", name: "E. Muñoz", position: "defender" },
			{ number: "24", name: "S. Barreto", position: "defender" },
			{ number: "28", name: "J. Di Lorenzo", position: "defender" },
			{ number: "5", name: "L. Rodríguez", position: "defender" },
			{ number: "3", name: "T. Ortega", position: "defender" },
			{ number: "16", name: "F. Bustos", position: "defender" },
			{ number: "4", name: "G. Asis", position: "defender" },
			{ number: "29", name: "L. Romero", position: "midfielder" },
			{ number: "21", name: "C. Benavidez", position: "midfielder" },
			{ number: "27", name: "J. Pacchini", position: "midfielder" },
			{ number: "23", name: "D. Blanco", position: "midfielder" },
			{ number: "8", name: "P. Hernández", position: "midfielder" },
			{ number: "14", name: "L. González", position: "midfielder" },
			{ number: "15", name: "A. Soñora", position: "midfielder" },
			{ number: "22", name: "F. Martínez", position: "midfielder" },
			{ number: "9", name: "A. Velasco", position: "forward" },
			{ number: "11", name: "J. Menéndez", position: "forward" },
			{ number: "7", name: "A. Roa", position: "forward" },
			{ number: "17", name: "G. Togni", position: "forward" },
			{ number: "30", name: "B. Martínez", position: "forward" },
			{ number: "-", name: "S. Palacios", position: "forward" },
			{ number: "20", name: "M. Del Castillo", position: "forward" },
			{ number: "18", name: "S. Romero", position: "forward" },
			{ number: "19", name: "N. Messiniti", position: "forward" },

		]
	},
	{
		teamName: "lanus",
		players: [
			{ number: "20", name: "R. Ríos Novo", position: "goalkeeper" },
			{ number: "15", name: "L. Acosta", position: "goalkeeper" },
			{ number: "1", name: "L. Morales", position: "goalkeeper" },
			{ number: "2", name: "A. Pérez", position: "defender" },
			{ number: "3", name: "G. Burdisso", position: "defender" },
			{ number: "6", name: "K. Lomónaco", position: "defender" },
			{ number: "29", name: "N. Thaller", position: "defender" },
			{ number: "22", name: "M. Pérez", position: "defender" },
			{ number: "40", name: "O. N'Dong", position: "defender" },
			{ number: "13", name: "J. Aude", position: "defender" },
			{ number: "25", name: "A. Bernabéi", position: "defender" },
			{ number: "17", name: "A. Tabares", position: "defender" },
			{ number: "35", name: "B. Aguirre", position: "defender" },
			{ number: "26", name: "L. Di Placido", position: "defender" },
			{ number: "4", name: "J. Gómez", position: "defender" },
			{ number: "-", name: "G. Carrasco", position: "defender" },
			{ number: "24", name: "N. Morgantini", position: "defender" },
			{ number: "37", name: "I. Cechi", position: "midfielder" },
			{ number: "19", name: "F. Quignón", position: "midfielder" },
			{ number: "14", name: "C. Núñez", position: "midfielder" },
			{ number: "8", name: "T. Belmonte", position: "midfielder" },
			{ number: "23", name: "L. Vera", position: "midfielder" },
			{ number: "-", name: "F. Barrientos", position: "midfielder" },
			{ number: "11", name: "M. Esquivel", position: "midfielder" },
			{ number: "34", name: "F. Pérez", position: "midfielder" },
			{ number: "30", name: "P. Aranda", position: "midfielder" },
			{ number: "7", name: "L. Acosta", position: "forward" },
			{ number: "21", name: "F. Orozco", position: "forward" },
			{ number: "-", name: "J. Sinisterra", position: "forward" },
			{ number: "10", name: "P. de La Vega", position: "forward" },
			{ number: "18", name: "J. Krilanovich", position: "forward" },
			{ number: "28", name: "G. Torres", position: "forward" },
			{ number: "33", name: "N. Orsini", position: "forward" },
			{ number: "36", name: "L. Varaldo", position: "forward" },
			{ number: "9", name: "J. Sand", position: "forward" },
			{ number: "41", name: "L. Besozzi", position: "forward" },

		]
	},
	{
		teamName: "newells",
		players: [
			{ number: "1", name: "A. Aguerre", position: "goalkeeper" },
			{ number: "23", name: "W. Barlasina", position: "goalkeeper" },
			{ number: "-", name: "Y. Cabral", position: "defender" },
			{ number: "2", name: "M. Guanini", position: "defender" },
			{ number: "22", name: "M. Capasso", position: "defender" },
			{ number: "24", name: "F. Fontanini", position: "defender" },
			{ number: "6", name: "S. Gentiletti", position: "defender" },
			{ number: "19", name: "F. Mansilla", position: "defender" },
			{ number: "28", name: "M. Bíttolo", position: "defender" },
			{ number: "33", name: "M. Orihuela", position: "defender" },
			{ number: "29", name: "B. Calderara", position: "defender" },
			{ number: "35", name: "F. Nadalín", position: "defender" },
			{ number: "20", name: "J. Fernández", position: "midfielder" },
			{ number: "30", name: "M. Maccari", position: "midfielder" },
			{ number: "43", name: "A. Moreno", position: "midfielder" },
			{ number: "13", name: "J. Sforza", position: "midfielder" },
			{ number: "31", name: "J. Cacciabue", position: "midfielder" },
			{ number: "8", name: "P. Pérez", position: "midfielder" },
			{ number: "-", name: "B. Rivero", position: "midfielder" },
			{ number: "36", name: "N. Castro", position: "midfielder" },
			{ number: "41", name: "M. Llano", position: "midfielder" },
			{ number: "10", name: "M. Formica", position: "midfielder" },
			{ number: "21", name: "D. Rodríguez", position: "midfielder" },
			{ number: "-", name: "C. Insaurralde", position: "forward" },
			{ number: "11", name: "Maxi Rodríguez", position: "forward" },
			{ number: "26", name: "R. Sordo", position: "forward" },
			{ number: "44", name: "F. González", position: "forward" },
			{ number: "-", name: "J. Marcioni", position: "forward" },
			{ number: "25", name: "E. Cabrera", position: "forward" },
			{ number: "32", name: "I. Scocco", position: "forward" },
			{ number: "14", name: "A. Rodríguez", position: "forward" },

		]
	},
	{
		teamName: "patronato",
		players: [
			{ number: "-", name: "M. Ibáñez", position: "goalkeeper" },
			{ number: "31", name: "D. Sappa", position: "goalkeeper" },
			{ number: "21", name: "F. Costa", position: "goalkeeper" },
			{ number: "1", name: "F. Rivasseau", position: "goalkeeper" },
			{ number: "28", name: "G. Canto", position: "defender" },
			{ number: "2", name: "D. Gissi", position: "defender" },
			{ number: "3", name: "O. Benítez", position: "defender" },
			{ number: "30", name: "L. Kruspzky", position: "defender" },
			{ number: "23", name: "B. Urribarri", position: "defender" },
			{ number: "6", name: "B. Negro", position: "defender" },
			{ number: "4", name: "C. Chimino", position: "defender" },
			{ number: "5", name: "L. Marín", position: "defender" },
			{ number: "7", name: "L. Geminiani", position: "defender" },
			{ number: "-", name: "J. Barinaga", position: "midfielder" },
			{ number: "-", name: "A. Pastorelli", position: "midfielder" },
			{ number: "-", name: "F. Leys", position: "midfielder" },
			{ number: "24", name: "D. Lemos", position: "midfielder" },
			{ number: "13", name: "B. Nievas", position: "midfielder" },
			{ number: "-", name: "H. Canteros", position: "midfielder" },
			{ number: "33", name: "L. Torres", position: "midfielder" },
			{ number: "39", name: "M. Gonzalez", position: "midfielder" },
			{ number: "22", name: "J. Ortiz", position: "midfielder" },
			{ number: "14", name: "F. Luna", position: "midfielder" },
			{ number: "11", name: "S. Briñone", position: "midfielder" },
			{ number: "37", name: "F. Dettler", position: "forward" },
			{ number: "29", name: "N. Delgadillo", position: "forward" },
			{ number: "40", name: "A. Guiffrey", position: "forward" },
			{ number: "-", name: "G. Gudiño", position: "forward" },
			{ number: "10", name: "L. Comas", position: "forward" },
			{ number: "20", name: "J. Arias", position: "forward" },
			{ number: "9", name: "G. Rivero", position: "forward" },
			{ number: "18", name: "J. Barreto", position: "forward" },
			{ number: "-", name: "N. Franco", position: "forward" },

		]
	},
	{
		teamName: "racing",
		players: [
			{ number: "1", name: "G. Arias", position: "goalkeeper" },
			{ number: "25", name: "G. Gómez", position: "goalkeeper" },
			{ number: "23", name: "N. Domínguez", position: "defender" },
			{ number: "30", name: "L. Sigali", position: "defender" },
			{ number: "6", name: "L. Orbán", position: "defender" },
			{ number: "16", name: "M. Martínez", position: "defender" },
			{ number: "32", name: "E. Machuca", position: "defender" },
			{ number: "3", name: "A. Soto", position: "defender" },
			{ number: "5", name: "E. Mena", position: "defender" },
			{ number: "18", name: "E. Schelotto", position: "defender" },
			{ number: "4", name: "I. Pillud", position: "defender" },
			{ number: "2", name: "J. Cáceres", position: "defender" },
			{ number: "19", name: "L. Miranda", position: "midfielder" },
			{ number: "21", name: "M. Díaz", position: "midfielder" },
			{ number: "8", name: "F. Domínguez", position: "midfielder" },
			{ number: "42", name: "P. Tanda", position: "midfielder" },
			{ number: "24", name: "J. López", position: "midfielder" },
			{ number: "27", name: "T. Banega", position: "midfielder" },
			{ number: "34", name: "L. Andrada", position: "midfielder" },
			{ number: "11", name: "Á. Gómez", position: "midfielder" },
			{ number: "26", name: "C. Alcaraz", position: "midfielder" },
			{ number: "33", name: "S. Sánchez", position: "midfielder" },
			{ number: "10", name: "M. Rojas", position: "midfielder" },
			{ number: "-", name: "T. Chancalay", position: "forward" },
			{ number: "35", name: "L. Melgarejo", position: "forward" },
			{ number: "7", name: "H. Fértoli", position: "forward" },
			{ number: "17", name: "B. Garré", position: "forward" },
			{ number: "38", name: "E. Cardozo", position: "forward" },
			{ number: "-", name: "M. Lovera", position: "forward" },
			{ number: "29", name: "N. Reniero", position: "forward" },
			{ number: "9", name: "J. Cristaldo", position: "forward" },
			{ number: "20", name: "D. Cvitanich", position: "forward" },
			{ number: "14", name: "S. Godoy", position: "forward" },

		]
	},
	{
		teamName: "river",
		players: [
			{ number: "1", name: "F. Armani", position: "goalkeeper" },
			{ number: "25", name: "E. Bologna", position: "goalkeeper" },
			{ number: "14", name: "G. Lux", position: "goalkeeper" },
			{ number: "2", name: "R. Rojas", position: "defender" },
			{ number: "17", name: "P. Díaz", position: "defender" },
			{ number: "22", name: "J. Pinola", position: "defender" },
			{ number: "3", name: "F. Angileri", position: "defender" },
			{ number: "20", name: "M. Casco", position: "defender" },
			{ number: "29", name: "G. Montiel", position: "defender" },
			{ number: "16", name: "J. Moreira", position: "defender" },
			{ number: "4", name: "E. López", position: "defender" },
			{ number: "13", name: "S. Sosa", position: "midfielder" },
			{ number: "5", name: "B. Zuculini", position: "midfielder" },
			{ number: "23", name: "L. Ponzio", position: "midfielder" },
			{ number: "10", name: "I. Fernández", position: "midfielder" },
			{ number: "21", name: "C. Ferreira", position: "midfielder" },
			{ number: "24", name: "E. Pérez", position: "midfielder" },
			{ number: "32", name: "T. Castro Ponce", position: "midfielder" },
			{ number: "11", name: "N. De La Cruz", position: "midfielder" },
			{ number: "8", name: "J. Carrascal", position: "midfielder" },
			{ number: "30", name: "B. Rollheiser", position: "forward" },
			{ number: "33", name: "S. Simón", position: "forward" },
			{ number: "19", name: "S. Borré", position: "forward" },
			{ number: "9", name: "J. Álvarez", position: "forward" },
			{ number: "7", name: "M. Suárez", position: "forward" },
			{ number: "15", name: "F. Girotti", position: "forward" },
			{ number: "18", name: "L. Beltrán", position: "forward" },

		]
	},
	{
		teamName: "central",
		players: [
			{ number: "1", name: "J. Ayala", position: "goalkeeper" },
			{ number: "30", name: "M. Miño", position: "goalkeeper" },
			{ number: "-", name: "J. Romero", position: "goalkeeper" },
			{ number: "31", name: "M. Maslovski", position: "goalkeeper" },
			{ number: "6", name: "J. Laso", position: "defender" },
			{ number: "32", name: "F. Almada", position: "defender" },
			{ number: "14", name: "D. Novaretti", position: "defender" },
			{ number: "33", name: "J. Bottinelli", position: "defender" },
			{ number: "3", name: "L. Blanco", position: "defender" },
			{ number: "13", name: "J. Mazzaco", position: "defender" },
			{ number: "4", name: "D. Martínez", position: "defender" },
			{ number: "20", name: "F. Torrent", position: "defender" },
			{ number: "21", name: "F. Rinaudo", position: "midfielder" },
			{ number: "5", name: "R. Villagra", position: "midfielder" },
			{ number: "25", name: "E. Ojeda", position: "midfielder" },
			{ number: "8", name: "D. Zabala", position: "midfielder" },
			{ number: "10", name: "E. Vecchio", position: "midfielder" },
			{ number: "18", name: "F. Lo Celso", position: "midfielder" },
			{ number: "19", name: "L. Ferreyra", position: "forward" },
			{ number: "7", name: "A. Marinelli", position: "forward" },
			{ number: "27", name: "G. Infantino", position: "forward" },
			{ number: "28", name: "L. Gamba", position: "forward" },
			{ number: "-", name: "M. Ruben", position: "forward" },
			{ number: "24", name: "A. Bonansea", position: "forward" },
			{ number: "23", name: "I. Russo", position: "forward" },
			{ number: "26", name: "L. Martínez Dupuy", position: "forward" },

		]
	},
	{
		teamName: "sanlorenzo",
		players: [
			{ number: "23", name: "F. Monetti", position: "goalkeeper" },
			{ number: "-", name: "J. Devecchi", position: "goalkeeper" },
			{ number: "12", name: "S. Torrico", position: "goalkeeper" },
			{ number: "13", name: "L. López Kaleniuk", position: "goalkeeper" },
			{ number: "30", name: "F. Flores", position: "defender" },
			{ number: "6", name: "F. Gattoni", position: "defender" },
			{ number: "2", name: "A. Donatti", position: "defender" },
			{ number: "-", name: "D. Braghieri", position: "defender" },
			{ number: "21", name: "R. Arias", position: "defender" },
			{ number: "32", name: "F. Coloccini", position: "defender" },
			{ number: "3", name: "B. Pittón", position: "defender" },
			{ number: "22", name: "G. Rojas", position: "defender" },
			{ number: "26", name: "N. Fernández Mercau", position: "defender" },
			{ number: "42", name: "M. Herrera", position: "defender" },
			{ number: "4", name: "G. Peruzzi", position: "defender" },
			{ number: "29", name: "V. Salazar", position: "defender" },
			{ number: "8", name: "D. Rodríguez", position: "midfielder" },
			{ number: "5", name: "L. Menossi", position: "midfielder" },
			{ number: "-", name: "M. Insaurralde", position: "midfielder" },
			{ number: "20", name: "J. Ramírez", position: "midfielder" },
			{ number: "35", name: "M. Palacios", position: "midfielder" },
			{ number: "10", name: "Ó. Romero", position: "midfielder" },
			{ number: "34", name: "J. Palacios", position: "midfielder" },
			{ number: "40", name: "A. Sabella", position: "midfielder" },
			{ number: "11", name: "Á. Romero", position: "forward" },
			{ number: "31", name: "L. Sequeira", position: "forward" },
			{ number: "16", name: "N. Fernández", position: "forward" },
			{ number: "33", name: "A. Díaz", position: "forward" },
			{ number: "17", name: "M. Peralta Bauer", position: "forward" },
			{ number: "9", name: "F. Di Santo", position: "forward" },
			{ number: "19", name: "A. Hausch", position: "forward" },

		]
	},
	{
		teamName: "talleres",
		players: [
			{ number: "-", name: "G. Herrera", position: "goalkeeper" },
			{ number: "21", name: "M. Díaz", position: "goalkeeper" },
			{ number: "33", name: "J. Blázquez", position: "goalkeeper" },
			{ number: "12", name: "F. Fragueda", position: "goalkeeper" },
			{ number: "6", name: "J. Komar", position: "defender" },
			{ number: "-", name: "R. Pérez", position: "defender" },
			{ number: "4", name: "P. Hincapié", position: "defender" },
			{ number: "-", name: "R. Paparelli", position: "defender" },
			{ number: "3", name: "J. Gandolfi", position: "defender" },
			{ number: "15", name: "E. Díaz", position: "defender" },
			{ number: "26", name: "F. Bersano", position: "defender" },
			{ number: "14", name: "N. Tenaglia", position: "defender" },
			{ number: "29", name: "A. Schott", position: "defender" },
			{ number: "13", name: "J. Malatini", position: "defender" },
			{ number: "16", name: "F. Mac Allister", position: "midfielder" },
			{ number: "5", name: "F. Navarro", position: "midfielder" },
			{ number: "27", name: "G. Torres", position: "midfielder" },
			{ number: "32", name: "T. Pochettino", position: "midfielder" },
			{ number: "8", name: "J. Méndez", position: "midfielder" },
			{ number: "10", name: "J. Soñora", position: "midfielder" },
			{ number: "18", name: "G. Álvez", position: "midfielder" },
			{ number: "39", name: "M. Mamani", position: "forward" },
			{ number: "20", name: "F. Fragapane", position: "forward" },
			{ number: "7", name: "D. Valoyes", position: "forward" },
			{ number: "28", name: "C. Auzqui", position: "forward" },
			{ number: "77", name: "Guilherme Parede", position: "forward" },
			{ number: "19", name: "M. Ortíz", position: "forward" },
			{ number: "-", name: "M. Santos", position: "forward" },
			{ number: "23", name: "M. Retegui", position: "forward" },
			{ number: "38", name: "M. Córdoba", position: "forward" },
			{ number: "17", name: "M. Arturia", position: "forward" },
			{ number: "9", name: "F. Cabral", position: "forward" },
			{ number: "36", name: "I. Lago", position: "forward" },

		]
	},
	{
		teamName: "union",
		players: [
			{ number: "25", name: "S. Moyano", position: "goalkeeper" },
			{ number: "-", name: "I. Arce", position: "goalkeeper" },
			{ number: "1", name: "M. Peano", position: "goalkeeper" },
			{ number: "-", name: "J. Papaleo", position: "goalkeeper" },
			{ number: "27", name: "J. Galván", position: "defender" },
			{ number: "6", name: "M. Nani", position: "defender" },
			{ number: "17", name: "B. Blasi", position: "defender" },
			{ number: "-", name: "P. Calderón", position: "defender" },
			{ number: "2", name: "F. Calderón", position: "defender" },
			{ number: "24", name: "F. Godoy", position: "defender" },
			{ number: "3", name: "C. Corvalán", position: "defender" },
			{ number: "4", name: "F. Gerometta", position: "defender" },
			{ number: "36", name: "F. Vera", position: "defender" },
			{ number: "30", name: "J. Nardoni", position: "midfielder" },
			{ number: "-", name: "M. Pittón", position: "midfielder" },
			{ number: "-", name: "N. Acevedo", position: "midfielder" },
			{ number: "33", name: "N. Leyes", position: "midfielder" },
			{ number: "21", name: "G. Comas", position: "midfielder" },
			{ number: "10", name: "G. Carabajal", position: "midfielder" },
			{ number: "45", name: "P. Palacio", position: "midfielder" },
			{ number: "32", name: "M. Borgnino", position: "forward" },
			{ number: "41", name: "G. González", position: "forward" },
			{ number: "22", name: "F. Troyansky", position: "forward" },
			{ number: "9", name: "F. Márquez", position: "forward" },
			{ number: "44", name: "D. Juárez", position: "forward" },
			{ number: "11", name: "J. García", position: "forward" },
			{ number: "38", name: "N. Andereggen", position: "forward" },
			{ number: "42", name: "M. Gallegos", position: "forward" },
			{ number: "26", name: "M. Cañete", position: "forward" },
			{ number: "16", name: "A. Pussetto", position: "forward" },
			{ number: "23", name: "M. Luna Diale", position: "forward" },

		]
	},
	{
		teamName: "velez",
		players: [
			{ number: "12", name: "L. Hoyos", position: "goalkeeper" },
			{ number: "22", name: "A. Domínguez", position: "goalkeeper" },
			{ number: "40", name: "M. Borgogno", position: "goalkeeper" },
			{ number: "29", name: "L. Abram", position: "defender" },
			{ number: "17", name: "L. Giannetti", position: "defender" },
			{ number: "2", name: "E. Amor", position: "defender" },
			{ number: "28", name: "M. Brizuela", position: "defender" },
			{ number: "5", name: "F. Ortega", position: "defender" },
			{ number: "-", name: "T. Cavanagh", position: "defender" },
			{ number: "24", name: "T. Guidara", position: "defender" },
			{ number: "4", name: "H. De La Fuente", position: "defender" },
			{ number: "20", name: "M. Pittón", position: "midfielder" },
			{ number: "27", name: "P. Galdames", position: "midfielder" },
			{ number: "15", name: "A. Mulet", position: "midfielder" },
			{ number: "8", name: "R. Álvarez", position: "midfielder" },
			{ number: "30", name: "F. Mancuello", position: "midfielder" },
			{ number: "21", name: "F. Cáseres", position: "midfielder" },
			{ number: "10", name: "T. Almada", position: "midfielder" },
			{ number: "11", name: "L. Janson", position: "forward" },
			{ number: "7", name: "R. Centurión", position: "forward" },
			{ number: "23", name: "A. Bouzat", position: "forward" },
			{ number: "14", name: "L. Orellano", position: "forward" },
			{ number: "19", name: "J. Lucero", position: "forward" },
			{ number: "18", name: "C. Tarragona", position: "forward" },
			{ number: "-", name: "N. Bazán", position: "forward" },
			{ number: "43", name: "J. Ramis", position: "forward" },
			{ number: "9", name: "F. Monzón", position: "forward" },

		]
	},
	{
		teamName: "platense",
		players: [
			{ number: "-", name: "J. De Olivera", position: "goalkeeper" },
			{ number: "-", name: "A. Desábato", position: "goalkeeper" },
			{ number: "-", name: "S. Callegari", position: "defender" },
			{ number: "-", name: "N. Zalazar", position: "defender" },
			{ number: "-", name: "I. Canuto", position: "defender" },
			{ number: "-", name: "L. Recalde", position: "defender" },
			{ number: "-", name: "N. Iribarren", position: "defender" },
			{ number: "-", name: "J. Infante", position: "defender" },
			{ number: "-", name: "B. Lluy", position: "defender" },
			{ number: "-", name: "F. Baldassarra", position: "midfielder" },
			{ number: "-", name: "P. Peréz", position: "midfielder" },
			{ number: "-", name: "T. Palacios", position: "midfielder" },
			{ number: "-", name: "R. Bochi", position: "midfielder" },
			{ number: "-", name: "H. Lamberti", position: "midfielder" },
			{ number: "-", name: "M. Bogado", position: "midfielder" },
			{ number: "-", name: "M. Vega", position: "midfielder" },
			{ number: "-", name: "J. Bustos", position: "midfielder" },
			{ number: "-", name: "A. Messidoro", position: "midfielder" },
			{ number: "-", name: "G. Pugliese", position: "forward" },
			{ number: "-", name: "N. Zeineddin", position: "forward" },
			{ number: "-", name: "I. Schor", position: "forward" },
			{ number: "-", name: "I. Puleio Araya", position: "forward" },
			{ number: "-", name: "J. Susvielles", position: "forward" },
			{ number: "-", name: "F. Curuchet", position: "forward" },
			{ number: "-", name: "D. Vega", position: "forward" },

		]
	},
	{
		teamName: "sarmiento",
		players: [
			{ number: "-", name: "M. Vicentini", position: "goalkeeper" },
			{ number: "-", name: "F. Daffonchio", position: "goalkeeper" },
			{ number: "-", name: "M. Herrera", position: "defender" },
			{ number: "-", name: "N. Bazzana", position: "defender" },
			{ number: "-", name: "F. Oliver", position: "defender" },
			{ number: "-", name: "J. Antonini", position: "defender" },
			{ number: "-", name: "F. Mancinelli", position: "defender" },
			{ number: "-", name: "B. Salvareschi", position: "defender" },
			{ number: "-", name: "F. Castet", position: "defender" },
			{ number: "-", name: "M. García", position: "defender" },
			{ number: "-", name: "L. Garnier", position: "defender" },
			{ number: "-", name: "J. Caviglia", position: "midfielder" },
			{ number: "-", name: "F. Vismara", position: "midfielder" },
			{ number: "-", name: "S. Quiroga", position: "midfielder" },
			{ number: "-", name: "C. Pombo", position: "midfielder" },
			{ number: "-", name: "F. Vázquez", position: "midfielder" },
			{ number: "-", name: "F. Bravo", position: "midfielder" },
			{ number: "-", name: "F. Montero", position: "midfielder" },
			{ number: "-", name: "G. Graciani", position: "midfielder" },
			{ number: "-", name: "F. Antonini", position: "midfielder" },
			{ number: "-", name: "G. Alanís", position: "midfielder" },
			{ number: "-", name: "M. Fornari", position: "midfielder" },
			{ number: "-", name: "M. Albertengo", position: "forward" },
			{ number: "-", name: "B. Borasi", position: "forward" },
			{ number: "-", name: "G. Vadalá", position: "forward" },
			{ number: "-", name: "J. Torres", position: "forward" },
			{ number: "-", name: "J. Franzoni", position: "forward" },
			{ number: "-", name: "J. Brea", position: "forward" },

		]
	},
]

export default teams