const teams = [
   {
      teamName: "aldosivi",
      players: [
         { number: "31", name: "Ingolotti", position: "goalkeeper" },
         { number: "1", name: "Pocrnjic", position: "goalkeeper" },
         { number: "35", name: "Assmann", position: "goalkeeper" },
         { number: "26", name: "Insúa", position: "defender" },
         { number: "6", name: "Schunke", position: "defender" },
         { number: "2", name: "Carli", position: "defender" },
         { number: "3", name: "López", position: "defender" },
         { number: "19", name: "Miers", position: "defender" },
         { number: "28", name: "Román", position: "defender" },
         { number: "13", name: "Insúa", position: "defender" },
         { number: "14", name: "Milo", position: "defender" },
         { number: "21", name: "Iñiguez", position: "defender" },
         { number: "25", name: "Yeri", position: "defender" },
         { number: "5", name: "Gil Romero", position: "midfielder" },
         { number: "27", name: "Villarreal", position: "midfielder" },
         { number: "24", name: "Lodico", position: "midfielder" },
         { number: "33", name: "Maciel", position: "midfielder" },
         { number: "10", name: "Grahl", position: "midfielder" },
         { number: "36", name: "Indacoechea", position: "midfielder" },
         { number: "32", name: "Becker", position: "midfielder" },
         { number: "18", name: "Perinciolo", position: "midfielder" },
         { number: "22", name: "Zarate", position: "midfielder" },
         { number: "41", name: "Panaro", position: "forward" },
         { number: "8", name: "Iritier", position: "forward" },
         { number: "26", name: "Guzmán", position: "forward" },
         { number: "30", name: "Pérez", position: "forward" },
         { number: "16", name: "Zacaría", position: "forward" },
         { number: "20", name: "Braida", position: "forward" },
         { number: "9", name: "Contreras", position: "forward" },
         { number: "7", name: "Andrada", position: "forward" },
         { number: "11", name: "Rinaldi", position: "forward" },
         { number: "17", name: "Di Yorio", position: "forward" },
         { number: "40", name: "Tobares", position: "forward" },
         { number: "29", name: "Ramírez", position: "forward" },

      ]
   },
   {
      teamName: "argentinos",
      players: [
         { number: "12", name: "Chaves", position: "goalkeeper" },
         { number: "-", name: "Lanzillotta", position: "goalkeeper" },
         { number: "1", name: "Finochietto", position: "goalkeeper" },
         { number: "31", name: "Acosta", position: "goalkeeper" },
         { number: "34", name: "Forastiero", position: "goalkeeper" },
         { number: "13", name: "Centurión", position: "defender" },
         { number: "16", name: "Quintana", position: "defender" },
         { number: "2", name: "Torrén", position: "defender" },
         { number: "29", name: "Di Cesare", position: "defender" },
         { number: "6", name: "Caruzzo", position: "defender" },
         { number: "24", name: "Gómez", position: "defender" },
         { number: "22", name: "Villalba", position: "defender" },
         { number: "4", name: "Mac Allister", position: "defender" },
         { number: "15", name: "Sandoval", position: "defender" },
         { number: "5", name: "Vera", position: "midfielder" },
         { number: "17", name: "Moyano", position: "midfielder" },
         { number: "26", name: "Romero", position: "midfielder" },
         { number: "18", name: "Sosa", position: "midfielder" },
         { number: "-", name: "Carabajal", position: "midfielder" },
         { number: "11", name: "Gómez", position: "midfielder" },
         { number: "8", name: "Colman", position: "midfielder" },
         { number: "-", name: "Andrade", position: "midfielder" },
         { number: "-", name: "Paiva", position: "midfielder" },
         { number: "21", name: "Mater", position: "midfielder" },
         { number: "25", name: "Coronel", position: "midfielder" },
         { number: "10", name: "Florentín", position: "midfielder" },
         { number: "28", name: "Silva", position: "forward" },
         { number: "-", name: "Pisano", position: "forward" },
         { number: "20", name: "Metilli", position: "forward" },
         { number: "-", name: "Cabrera", position: "forward" },
         { number: "14", name: "Saggiomo", position: "forward" },
         { number: "-", name: "Herrera", position: "forward" },
         { number: "9", name: "Ávalos", position: "forward" },
         { number: "27", name: "Hauche", position: "forward" },
         { number: "19", name: "Pucheta", position: "forward" },

      ]
   },
   {
      teamName: "arsenal",
      players: [
         { number: "1", name: "Navarro", position: "goalkeeper" },
         { number: "12", name: "Rivero", position: "goalkeeper" },
         { number: "22", name: "Balbuena", position: "defender" },
         { number: "14", name: "Carabajal", position: "defender" },
         { number: "6", name: "Suso", position: "defender" },
         { number: "33", name: "Bottinelli", position: "defender" },
         { number: "16", name: "Gariglio", position: "defender" },
         { number: "26", name: "Suárez", position: "defender" },
         { number: "3", name: "Papa", position: "defender" },
         { number: "18", name: "Navas", position: "defender" },
         { number: "29", name: "Benavídez", position: "defender" },
         { number: "4", name: "Abreliano", position: "defender" },
         { number: "27", name: "Kruspzky", position: "midfielder" },
         { number: "2", name: "Andrada", position: "midfielder" },
         { number: "5", name: "Méndez", position: "midfielder" },
         { number: "24", name: "Antilef", position: "midfielder" },
         { number: "8", name: "Soraire", position: "midfielder" },
         { number: "21", name: "Picco", position: "midfielder" },
         { number: "-", name: "Ortiz", position: "midfielder" },
         { number: "15", name: "Luna", position: "midfielder" },
         { number: "11", name: "Castro", position: "midfielder" },
         { number: "19", name: "Farioli", position: "midfielder" },
         { number: "10", name: "Necul", position: "midfielder" },
         { number: "31", name: "Alan Ruiz", position: "midfielder" },
         { number: "32", name: "Báez", position: "forward" },
         { number: "28", name: "Belloso", position: "forward" },
         { number: "9", name: "Albertengo", position: "forward" },
         { number: "20", name: "Candia", position: "forward" },
         { number: "17", name: "Sepúlveda", position: "forward" },
         { number: "7", name: "Miracco", position: "forward" },

      ]
   },
   {
      teamName: "atltucuman",
      players: [
         { number: "12", name: "Marchiori", position: "goalkeeper" },
         { number: "1", name: "Lucchetti", position: "goalkeeper" },
         { number: "20", name: "Pizzicanella", position: "goalkeeper" },
         { number: "24", name: "Ortiz", position: "defender" },
         { number: "6", name: "Osores", position: "defender" },
         { number: "-", name: "Vergini", position: "defender" },
         { number: "30", name: "Risso Patrón", position: "defender" },
         { number: "3", name: "Monzón", position: "defender" },
         { number: "2", name: "Ortiz", position: "defender" },
         { number: "4", name: "Toledo", position: "defender" },
         { number: "14", name: "Lagos", position: "defender" },
         { number: "7", name: "Mussis", position: "midfielder" },
         { number: "5", name: "Bustos", position: "midfielder" },
         { number: "21", name: "Erbes", position: "midfielder" },
         { number: "16", name: "Laméndola", position: "midfielder" },
         { number: "8", name: "Acosta", position: "midfielder" },
         { number: "23", name: "Carrera", position: "midfielder" },
         { number: "19", name: "Aguirre", position: "midfielder" },
         { number: "12", name: "Rosales", position: "midfielder" },
         { number: "10", name: "Heredia", position: "midfielder" },
         { number: "-", name: "Benítez", position: "forward" },
         { number: "28", name: "Romero", position: "forward" },
         { number: "11", name: "Alustiza", position: "forward" },
         { number: "9", name: "Lotti", position: "forward" },
         { number: "29", name: "Isa Luna", position: "forward" },
         { number: "18", name: "Ruiz Rodriguez", position: "forward" },
         { number: "22", name: "Toledo", position: "forward" },

      ]
   },
   {
      teamName: "banfield",
      players: [
         { number: "1", name: "Arboleda", position: "goalkeeper" },
         { number: "27", name: "Altamirano", position: "goalkeeper" },
         { number: "2", name: "Maldonado", position: "defender" },
         { number: "6", name: "Lollo", position: "defender" },
         { number: "19", name: "Sosa", position: "defender" },
         { number: "3", name: "Quinteros", position: "defender" },
         { number: "32", name: "Coronel", position: "defender" },
         { number: "24", name: "Gómez", position: "defender" },
         { number: "5", name: "Linares", position: "midfielder" },
         { number: "21", name: "Payero", position: "midfielder" },
         { number: "8", name: "Galoppo", position: "midfielder" },
         { number: "25", name: "Cabrera", position: "midfielder" },
         { number: "23", name: "Gutiérrez", position: "midfielder" },
         { number: "28", name: "González", position: "midfielder" },
         { number: "10", name: "Dátolo", position: "midfielder" },
         { number: "11", name: "Urzi", position: "forward" },
         { number: "17", name: "Cuero", position: "forward" },
         { number: "22", name: "Álvarez", position: "forward" },
         { number: "-", name: "Villagra", position: "forward" },
         { number: "7", name: "Bordagaray", position: "forward" },
         { number: "29", name: "Pons", position: "forward" },
         { number: "31", name: "Asenjo", position: "forward" },
         { number: "16", name: "Cruz", position: "forward" },

      ]
   },
   {
      teamName: "boca",
      players: [
         { number: "1", name: "Andrada", position: "goalkeeper" },
         { number: "28", name: "Roffo", position: "goalkeeper" },
         { number: "17", name: "Rossi", position: "goalkeeper" },
         { number: "13", name: "García", position: "goalkeeper" },
         { number: "6", name: "Rojo", position: "defender" },
         { number: "2", name: "López", position: "defender" },
         { number: "24", name: "Izquierdoz", position: "defender" },
         { number: "5", name: "Zambrano", position: "defender" },
         { number: "18", name: "Fabra", position: "defender" },
         { number: "3", name: "Mas", position: "defender" },
         { number: "29", name: "Jara", position: "defender" },
         { number: "4", name: "Buffarini", position: "defender" },
         { number: "35", name: "Giampaoli", position: "defender" },
         { number: "21", name: "Campuzano", position: "midfielder" },
         { number: "23", name: "González", position: "midfielder" },
         { number: "14", name: "Capaldo", position: "midfielder" },
         { number: "25", name: "Almendra", position: "midfielder" },
         { number: "33", name: "Varela", position: "midfielder" },
         { number: "32", name: "Medina", position: "midfielder" },
         { number: "8", name: "Cardona", position: "midfielder" },
         { number: "32", name: "Maroni", position: "midfielder" },
         { number: "16", name: "Molinas", position: "midfielder" },
         { number: "-", name: "Pavón", position: "forward" },
         { number: "22", name: "Villa", position: "forward" },
         { number: "34", name: "Obando", position: "forward" },
         { number: "11", name: "Salvio", position: "forward" },
         { number: "30", name: "Zeballos", position: "forward" },
         { number: "19", name: "Zárate", position: "forward" },
         { number: "10", name: "Tevez", position: "forward" },
         { number: "9", name: "Ábila", position: "forward" },
         { number: "27", name: "Soldano", position: "forward" },
         { number: "38", name: "Vázquez", position: "forward" },

      ]
   },
   {
      teamName: "cantralcdba",
      players: [
         { number: "32", name: "Mehring", position: "goalkeeper" },
         { number: "1", name: "Sánchez", position: "goalkeeper" },
         { number: "13", name: "Taborda", position: "goalkeeper" },
         { number: "44", name: "Maciel", position: "defender" },
         { number: "-", name: "Rentería", position: "defender" },
         { number: "4", name: "Salomón", position: "defender" },
         { number: "6", name: "Sbuttoni", position: "defender" },
         { number: "2", name: "Andueza", position: "defender" },
         { number: "19", name: "Acuña", position: "defender" },
         { number: "12", name: "Bay", position: "defender" },
         { number: "3", name: "Banegas", position: "defender" },
         { number: "25", name: "Bettini", position: "defender" },
         { number: "8", name: "González", position: "defender" },
         { number: "29", name: "Quílez", position: "defender" },
         { number: "24", name: "Vera Oviedo", position: "defender" },
         { number: "26", name: "Díaz", position: "defender" },
         { number: "40", name: "Pinto", position: "midfielder" },
         { number: "5", name: "Vega", position: "midfielder" },
         { number: "14", name: "Galeano", position: "midfielder" },
         { number: "39", name: "Montenegro", position: "midfielder" },
         { number: "16", name: "Rojas", position: "midfielder" },
         { number: "18", name: "Cerro", position: "midfielder" },
         { number: "11", name: "Fernández", position: "midfielder" },
         { number: "7", name: "Barraza", position: "midfielder" },
         { number: "20", name: "Barrios", position: "forward" },
         { number: "30", name: "Rosales", position: "forward" },
         { number: "27", name: "Lattanzio", position: "forward" },
         { number: "-", name: "Sequeira", position: "forward" },
         { number: "21", name: "Brochero", position: "forward" },
         { number: "23", name: "Ribas", position: "forward" },
         { number: "9", name: "Riaño", position: "forward" },
         { number: "28", name: "Argañaraz", position: "forward" },
         { number: "-", name: "Giménez", position: "forward" },

      ]
   },
   {
      teamName: "colon",
      players: [
         { number: "1", name: "Burián", position: "goalkeeper" },
         { number: "17", name: "Chicco", position: "goalkeeper" },
         { number: "22", name: "Hass", position: "goalkeeper" },
         { number: "2", name: "Bianchi", position: "defender" },
         { number: "6", name: "Goltz", position: "defender" },
         { number: "3", name: "Piovi", position: "defender" },
         { number: "-", name: "Acevedo", position: "defender" },
         { number: "33", name: "Garcés", position: "defender" },
         { number: "36", name: "Nardelli", position: "defender" },
         { number: "31", name: "Escobar", position: "defender" },
         { number: "40", name: "Delgado", position: "defender" },
         { number: "58", name: "Ibarra", position: "defender" },
         { number: "-", name: "Mura", position: "defender" },
         { number: "21", name: "Eric Meza", position: "defender" },
         { number: "14", name: "Lértora", position: "midfielder" },
         { number: "8", name: "Góez", position: "midfielder" },
         { number: "34", name: "Moreyra", position: "midfielder" },
         { number: "-", name: "Ferreira", position: "midfielder" },
         { number: "29", name: "Aliendro", position: "midfielder" },
         { number: "11", name: "Castro", position: "midfielder" },
         { number: "30", name: "Pierotti", position: "midfielder" },
         { number: "35", name: "Farias", position: "midfielder" },
         { number: "23", name: "Bernardi", position: "forward" },
         { number: "10", name: "Rodríguez", position: "forward" },
         { number: "38", name: "Fernández", position: "forward" },
         { number: "9", name: "Leguizamón", position: "forward" },
         { number: "19", name: "Morelo", position: "forward" },
         { number: "32", name: "Sandoval", position: "forward" },

      ]
   },
   {
      teamName: "defyjusticia",
      players: [
         { number: "22", name: "Unsain", position: "goalkeeper" },
         { number: "1", name: "Ledesma", position: "goalkeeper" },
         { number: "2", name: "Frías", position: "defender" },
         { number: "6", name: "Paredes", position: "defender" },
         { number: "-", name: "Meza", position: "defender" },
         { number: "28", name: "Rodríguez", position: "defender" },
         { number: "13", name: "Herrera", position: "defender" },
         { number: "4", name: "Sienra", position: "defender" },
         { number: "37", name: "Brítez", position: "defender" },
         { number: "33", name: "Gallardo", position: "defender" },
         { number: "3", name: "Benítez", position: "defender" },
         { number: "24", name: "Duarte", position: "defender" },
         { number: "25", name: "Breitenbruch", position: "defender" },
         { number: "-", name: "Tripichio", position: "defender" },
         { number: "40", name: "Echevarria", position: "midfielder" },
         { number: "34", name: "Fernández", position: "midfielder" },
         { number: "30", name: "Loaiza", position: "midfielder" },
         { number: "35", name: "Larralde", position: "midfielder" },
         { number: "16", name: "Escalante", position: "midfielder" },
         { number: "-", name: "Martínez", position: "midfielder" },
         { number: "8", name: "Farías", position: "midfielder" },
         { number: "32", name: "Luayza", position: "midfielder" },
         { number: "10", name: "Ortiz", position: "midfielder" },
         { number: "23", name: "Isnaldo", position: "forward" },
         { number: "29", name: "Pizzini", position: "forward" },
         { number: "31", name: "Romero", position: "forward" },
         { number: "12", name: "Ciro Rius", position: "forward" },
         { number: "7", name: "González", position: "forward" },
         { number: "20", name: "Bou", position: "forward" },
         { number: "9", name: "Merentiel", position: "forward" },
         { number: "19", name: "Hachen", position: "forward" },

      ]
   },
   {
      teamName: "estudiantes",
      players: [
         { number: "21", name: "Andújar", position: "goalkeeper" },
         { number: "1", name: "Pourtau", position: "goalkeeper" },
         { number: "12", name: "González", position: "goalkeeper" },
         { number: "-", name: "Rogel", position: "defender" },
         { number: "2", name: "Tobio", position: "defender" },
         { number: "18", name: "Noguera", position: "defender" },
         { number: "6", name: "Colombo", position: "defender" },
         { number: "17", name: "Guzmán", position: "defender" },
         { number: "29", name: "Squadrone", position: "defender" },
         { number: "14", name: "Sánchez Miño", position: "defender" },
         { number: "15", name: "Pasquini", position: "defender" },
         { number: "4", name: "Godoy", position: "defender" },
         { number: "30", name: "Rodríguez", position: "midfielder" },
         { number: "24", name: "Ayala", position: "midfielder" },
         { number: "5", name: "Gómez", position: "midfielder" },
         { number: "31", name: "Romero", position: "midfielder" },
         { number: "34", name: "Kociubinski", position: "midfielder" },
         { number: "23", name: "Kalinski", position: "midfielder" },
         { number: "28", name: "Castro", position: "midfielder" },
         { number: "20", name: "García", position: "midfielder" },
         { number: "10", name: "Díaz", position: "midfielder" },
         { number: "44", name: "Obregón", position: "midfielder" },
         { number: "19", name: "Rodríguez", position: "forward" },
         { number: "16", name: "Sarmiento", position: "forward" },
         { number: "8", name: "Á. González", position: "forward" },
         { number: "27", name: "Díaz", position: "forward" },
         { number: "7", name: "Cauteruccio", position: "forward" },
         { number: "9", name: "González", position: "forward" },
         { number: "22", name: "Sabbag", position: "forward" },
         { number: "26", name: "Apaolaza", position: "forward" },
         { number: "33", name: "Di Pizio", position: "forward" },

      ]
   },
   {
      teamName: "gimnasia",
      players: [
         { number: "17", name: "Rey", position: "goalkeeper" },
         { number: "1", name: "Durso", position: "goalkeeper" },
         { number: "12", name: "Insfrán", position: "goalkeeper" },
         { number: "24", name: "Guiffrey", position: "defender" },
         { number: "23", name: "Coronel", position: "defender" },
         { number: "38", name: "Fernández", position: "defender" },
         { number: "35", name: "Palazzo", position: "defender" },
         { number: "32", name: "Melluso", position: "defender" },
         { number: "25", name: "Licht", position: "defender" },
         { number: "57", name: "Weigandt", position: "defender" },
         { number: "4", name: "Morales", position: "defender" },
         { number: "5", name: "Mancilla", position: "midfielder" },
         { number: "16", name: "Ayala", position: "midfielder" },
         { number: "36", name: "Miramón", position: "midfielder" },
         { number: "-", name: "Cecchini", position: "midfielder" },
         { number: "22", name: "Miranda", position: "midfielder" },
         { number: "15", name: "Alemán", position: "midfielder" },
         { number: "31", name: "Pérez García", position: "midfielder" },
         { number: "21", name: "Chávez", position: "midfielder" },
         { number: "-", name: "Tijanovich", position: "forward" },
         { number: "-", name: "Gómez", position: "forward" },
         { number: "7", name: "Carbonero", position: "forward" },
         { number: "43", name: "Ramírez", position: "forward" },
         { number: "-", name: "Comba", position: "forward" },
         { number: "9", name: "Contin", position: "forward" },
         { number: "18", name: "Barrios", position: "forward" },
         { number: "37", name: "Cocimano", position: "forward" },

      ]
   },
   {
      teamName: "godoycruz",
      players: [
         { number: "1", name: "Ramírez", position: "goalkeeper" },
         { number: "12", name: "Espínola", position: "goalkeeper" },
         { number: "23", name: "Ibáñez", position: "goalkeeper" },
         { number: "22", name: "Ferrari", position: "defender" },
         { number: "2", name: "Goñi", position: "defender" },
         { number: "24", name: "Romero", position: "defender" },
         { number: "37", name: "Aguirre", position: "defender" },
         { number: "26", name: "Pérez", position: "defender" },
         { number: "3", name: "González", position: "defender" },
         { number: "6", name: "Escobar", position: "defender" },
         { number: "-", name: "Arena", position: "defender" },
         { number: "28", name: "López", position: "defender" },
         { number: "29", name: "Silva", position: "defender" },
         { number: "5", name: "Cartagena", position: "midfielder" },
         { number: "4", name: "Cirigliano", position: "midfielder" },
         { number: "31", name: "Álvarez", position: "midfielder" },
         { number: "32", name: "Abrego", position: "midfielder" },
         { number: "34", name: "Pizarro", position: "midfielder" },
         { number: "19", name: "Henríquez", position: "midfielder" },
         { number: "10", name: "Burgoa", position: "midfielder" },
         { number: "11", name: "Ojeda", position: "forward" },
         { number: "-", name: "Ramis", position: "forward" },
         { number: "7", name: "Chalá", position: "forward" },
         { number: "33", name: "Bullaude", position: "forward" },
         { number: "8", name: "Tesuri", position: "forward" },
         { number: "20", name: "Cantero", position: "forward" },
         { number: "15", name: "González", position: "forward" },
         { number: "9", name: "Badaloni", position: "forward" },
         { number: "27", name: "Lomónaco", position: "forward" },

      ]
   },
   {
      teamName: "huracan",
      players: [
         { number: "1", name: "Cambeses", position: "goalkeeper" },
         { number: "22", name: "Mendive", position: "goalkeeper" },
         { number: "27", name: "Ferrario", position: "goalkeeper" },
         { number: "32", name: "Meza", position: "goalkeeper" },
         { number: "-", name: "Moya", position: "defender" },
         { number: "23", name: "Merolla", position: "defender" },
         { number: "2", name: "Civelli", position: "defender" },
         { number: "13", name: "Pérez", position: "defender" },
         { number: "-", name: "Erquiaga", position: "defender" },
         { number: "25", name: "Ibáñez", position: "defender" },
         { number: "3", name: "Grimi", position: "defender" },
         { number: "26", name: "Bonifacio", position: "defender" },
         { number: "4", name: "Lozano", position: "defender" },
         { number: "-", name: "Yacob", position: "midfielder" },
         { number: "8", name: "Arregui", position: "midfielder" },
         { number: "21", name: "Rolón", position: "midfielder" },
         { number: "15", name: "Marín", position: "midfielder" },
         { number: "30", name: "Mercado", position: "midfielder" },
         { number: "5", name: "Hezze", position: "midfielder" },
         { number: "11", name: "Cristaldo", position: "midfielder" },
         { number: "14", name: "Navarro", position: "midfielder" },
         { number: "42", name: "Pablo Oro", position: "midfielder" },
         { number: "18", name: "Toranzo", position: "midfielder" },
         { number: "7", name: "Garro", position: "forward" },
         { number: "43", name: "Curruhinca", position: "forward" },
         { number: "16", name: "Maidana", position: "forward" },
         { number: "10", name: "Norberto Briasco", position: "forward" },
         { number: "12", name: "Ramírez", position: "forward" },
         { number: "39", name: "Cabral", position: "forward" },
         { number: "17", name: "Núñez", position: "forward" },
         { number: "9", name: "Chávez", position: "forward" },
         { number: "19", name: "Cordero", position: "forward" },
         { number: "24", name: "Coniglio", position: "forward" },
         { number: "29", name: "Mendoza", position: "forward" },

      ]
   },
   {
      teamName: "independiente",
      players: [
         { number: "1", name: "Sosa", position: "goalkeeper" },
         { number: "13", name: "Álvarez", position: "goalkeeper" },
         { number: "12", name: "Bacchia", position: "goalkeeper" },
         { number: "2", name: "Franco", position: "defender" },
         { number: "6", name: "Muñoz", position: "defender" },
         { number: "24", name: "Barreto", position: "defender" },
         { number: "33", name: "Insaurralde", position: "defender" },
         { number: "5", name: "Rodríguez", position: "defender" },
         { number: "3", name: "Ortega", position: "defender" },
         { number: "16", name: "Bustos", position: "defender" },
         { number: "4", name: "Asis", position: "defender" },
         { number: "29", name: "Romero", position: "midfielder" },
         { number: "21", name: "Benavidez", position: "midfielder" },
         { number: "27", name: "Pacchini", position: "midfielder" },
         { number: "23", name: "Blanco", position: "midfielder" },
         { number: "14", name: "González", position: "midfielder" },
         { number: "15", name: "Soñora", position: "midfielder" },
         { number: "8", name: "Hernández", position: "midfielder" },
         { number: "22", name: "Martínez", position: "midfielder" },
         { number: "9", name: "Velasco", position: "forward" },
         { number: "11", name: "Menéndez", position: "forward" },
         { number: "7", name: "Roa", position: "forward" },
         { number: "17", name: "Togni", position: "forward" },
         { number: "30", name: "Martínez", position: "forward" },
         { number: "34", name: "Palacios", position: "forward" },
         { number: "20", name: "Del Castillo", position: "forward" },
         { number: "18", name: "Romero", position: "forward" },
         { number: "19", name: "Messiniti", position: "forward" },
         { number: "37", name: "Landaburu", position: "forward" },

      ]
   },
   {
      teamName: "lanus",
      players: [
         { number: "1", name: "Morales", position: "goalkeeper" },
         { number: "20", name: "Ríos Novo", position: "goalkeeper" },
         { number: "15", name: "Acosta", position: "goalkeeper" },
         { number: "2", name: "Pérez", position: "defender" },
         { number: "3", name: "Burdisso", position: "defender" },
         { number: "6", name: "Lomónaco", position: "defender" },
         { number: "29", name: "Thaller", position: "defender" },
         { number: "22", name: "Pérez", position: "defender" },
         { number: "40", name: "N'Dong", position: "defender" },
         { number: "25", name: "Bernabéi", position: "defender" },
         { number: "35", name: "Aguirre", position: "defender" },
         { number: "13", name: "Aude", position: "defender" },
         { number: "17", name: "Tabares", position: "defender" },
         { number: "26", name: "Di Placido", position: "defender" },
         { number: "4", name: "Gómez", position: "defender" },
         { number: "-", name: "Carrasco", position: "defender" },
         { number: "24", name: "Morgantini", position: "defender" },
         { number: "19", name: "Quignón", position: "midfielder" },
         { number: "8", name: "Belmonte", position: "midfielder" },
         { number: "23", name: "Vera", position: "midfielder" },
         { number: "11", name: "Esquivel", position: "midfielder" },
         { number: "34", name: "Pérez", position: "midfielder" },
         { number: "30", name: "Aranda", position: "midfielder" },
         { number: "21", name: "Orozco", position: "forward" },
         { number: "7", name: "Acosta", position: "forward" },
         { number: "10", name: "de La Vega", position: "forward" },
         { number: "18", name: "Krilanovich", position: "forward" },
         { number: "33", name: "Orsini", position: "forward" },
         { number: "36", name: "Varaldo", position: "forward" },
         { number: "9", name: "Sand", position: "forward" },
         { number: "41", name: "Besozzi", position: "forward" },

      ]
   },
   {
      teamName: "newells",
      players: [
         { number: "1", name: "Aguerre", position: "goalkeeper" },
         { number: "12", name: "Macagno", position: "goalkeeper" },
         { number: "23", name: "Barlasina", position: "goalkeeper" },
         { number: "-", name: "Lema", position: "defender" },
         { number: "16", name: "Cabral", position: "defender" },
         { number: "2", name: "Guanini", position: "defender" },
         { number: "22", name: "Capasso", position: "defender" },
         { number: "6", name: "Gentiletti", position: "defender" },
         { number: "19", name: "Mansilla", position: "defender" },
         { number: "28", name: "Bíttolo", position: "defender" },
         { number: "33", name: "Orihuela", position: "defender" },
         { number: "-", name: "Escobar", position: "defender" },
         { number: "35", name: "Nadalín", position: "defender" },
         { number: "41", name: "Llano", position: "defender" },
         { number: "20", name: "Fernández", position: "midfielder" },
         { number: "30", name: "Maccari", position: "midfielder" },
         { number: "13", name: "Sforza", position: "midfielder" },
         { number: "31", name: "Cacciabue", position: "midfielder" },
         { number: "8", name: "Pérez", position: "midfielder" },
         { number: "-", name: "Belluschi", position: "midfielder" },
         { number: "24", name: "Rivero", position: "midfielder" },
         { number: "36", name: "Castro", position: "midfielder" },
         { number: "10", name: "Formica", position: "midfielder" },
         { number: "21", name: "Rodríguez", position: "midfielder" },
         { number: "44", name: "González", position: "forward" },
         { number: "-", name: "Rotondi", position: "forward" },
         { number: "11", name: "Maxi Rodríguez", position: "forward" },
         { number: "-", name: "Insaurralde", position: "forward" },
         { number: "26", name: "Sordo", position: "forward" },
         { number: "39", name: "Marcioni", position: "forward" },
         { number: "25", name: "Cabrera", position: "forward" },
         { number: "7", name: "Cingolani", position: "forward" },
         { number: "-", name: "Cristaldo", position: "forward" },
         { number: "14", name: "Rodríguez", position: "forward" },
         { number: "32", name: "Scocco", position: "forward" },

      ]
   },
   {
      teamName: "patronato",
      players: [
         { number: "12", name: "Ibáñez", position: "goalkeeper" },
         { number: "21", name: "Costa", position: "goalkeeper" },
         { number: "1", name: "Rivasseau", position: "goalkeeper" },
         { number: "-", name: "Ojeda", position: "defender" },
         { number: "3", name: "Benítez", position: "defender" },
         { number: "28", name: "Canto", position: "defender" },
         { number: "2", name: "Gissi", position: "defender" },
         { number: "-", name: "García", position: "defender" },
         { number: "30", name: "Kruspzky", position: "defender" },
         { number: "6", name: "Negro", position: "defender" },
         { number: "23", name: "Urribarri", position: "defender" },
         { number: "5", name: "Marín", position: "defender" },
         { number: "4", name: "Geminiani", position: "defender" },
         { number: "-", name: "Garay", position: "midfielder" },
         { number: "32", name: "Leys", position: "midfielder" },
         { number: "24", name: "Lemos", position: "midfielder" },
         { number: "13", name: "Nievas", position: "midfielder" },
         { number: "-", name: "Canteros", position: "midfielder" },
         { number: "33", name: "Torres", position: "midfielder" },
         { number: "39", name: "Gonzalez", position: "midfielder" },
         { number: "14", name: "Luna", position: "midfielder" },
         { number: "-", name: "Briñone", position: "midfielder" },
         { number: "16", name: "Barinaga", position: "midfielder" },
         { number: "-", name: "Palavecino", position: "midfielder" },
         { number: "37", name: "Dettler", position: "forward" },
         { number: "11", name: "Delgadillo", position: "forward" },
         { number: "25", name: "Pastorelli", position: "forward" },
         { number: "40", name: "Guiffrey", position: "forward" },
         { number: "8", name: "Gudiño", position: "forward" },
         { number: "-", name: "Bandiera", position: "forward" },
         { number: "10", name: "Comas", position: "forward" },
         { number: "20", name: "Arias", position: "forward" },
         { number: "9", name: "Rivero", position: "forward" },
         { number: "-", name: "Sosa", position: "forward" },
         { number: "18", name: "Barreto", position: "forward" },
         { number: "19", name: "Franco", position: "forward" },

      ]
   },
   {
      teamName: "racing",
      players: [
         { number: "1", name: "Arias", position: "goalkeeper" },
         { number: "25", name: "Gómez", position: "goalkeeper" },
         { number: "-", name: "Tagliamonte", position: "goalkeeper" },
         { number: "23", name: "Domínguez", position: "defender" },
         { number: "30", name: "Sigali", position: "defender" },
         { number: "6", name: "Orbán", position: "defender" },
         { number: "-", name: "Novillo", position: "defender" },
         { number: "16", name: "Martínez", position: "defender" },
         { number: "3", name: "Soto", position: "defender" },
         { number: "5", name: "Mena", position: "defender" },
         { number: "18", name: "Schelotto", position: "defender" },
         { number: "4", name: "Pillud", position: "defender" },
         { number: "2", name: "Cáceres", position: "defender" },
         { number: "19", name: "Miranda", position: "midfielder" },
         { number: "21", name: "Díaz", position: "midfielder" },
         { number: "31", name: "Gutiérrez", position: "midfielder" },
         { number: "8", name: "Domínguez", position: "midfielder" },
         { number: "42", name: "Tanda", position: "midfielder" },
         { number: "29", name: "Moreno", position: "midfielder" },
         { number: "26", name: "Alcaraz", position: "midfielder" },
         { number: "27", name: "Banega", position: "midfielder" },
         { number: "24", name: "López", position: "midfielder" },
         { number: "34", name: "Andrada", position: "midfielder" },
         { number: "11", name: "Á. Gómez", position: "midfielder" },
         { number: "33", name: "Sánchez", position: "midfielder" },
         { number: "10", name: "Rojas", position: "midfielder" },
         { number: "28", name: "Chancalay", position: "forward" },
         { number: "35", name: "Melgarejo", position: "forward" },
         { number: "7", name: "Fértoli", position: "forward" },
         { number: "17", name: "Garré", position: "forward" },
         { number: "9", name: "Copetti", position: "forward" },
         { number: "34", name: "Lovera", position: "forward" },
         { number: "29", name: "Reniero", position: "forward" },
         { number: "20", name: "Cvitanich", position: "forward" },
         { number: "14", name: "Godoy", position: "forward" },

      ]
   },
   {
      teamName: "river",
      players: [
         { number: "1", name: "Armani", position: "goalkeeper" },
         { number: "25", name: "Bologna", position: "goalkeeper" },
         { number: "14", name: "Lux", position: "goalkeeper" },
         { number: "2", name: "Rojas", position: "defender" },
         { number: "17", name: "Díaz", position: "defender" },
         { number: "6", name: "Martínez", position: "defender" },
         { number: "4", name: "Maidana", position: "defender" },
         { number: "22", name: "Pinola", position: "defender" },
         { number: "3", name: "Angileri", position: "defender" },
         { number: "20", name: "Casco", position: "defender" },
         { number: "29", name: "Montiel", position: "defender" },
         { number: "16", name: "Alex Vigo", position: "defender" },
         { number: "38", name: "Moreira", position: "defender" },
         { number: "5", name: "Zuculini", position: "midfielder" },
         { number: "24", name: "Pérez", position: "midfielder" },
         { number: "23", name: "Ponzio", position: "midfielder" },
         { number: "26", name: "Fernández", position: "midfielder" },
         { number: "26", name: "Paradela", position: "midfielder" },
         { number: "11", name: "De La Cruz", position: "midfielder" },
         { number: "10", name: "Carrascal", position: "midfielder" },
         { number: "8", name: "Palavecino", position: "midfielder" },
         { number: "30", name: "Rollheiser", position: "forward" },
         { number: "31", name: "Simón", position: "forward" },
         { number: "19", name: "Borré", position: "forward" },
         { number: "9", name: "Álvarez", position: "forward" },
         { number: "7", name: "Suárez", position: "forward" },
         { number: "27", name: "Fontana", position: "forward" },
         { number: "15", name: "Girotti", position: "forward" },
         { number: "18", name: "Beltrán", position: "forward" },

      ]
   },
   {
      teamName: "central",
      players: [
         { number: "19", name: "Broun", position: "goalkeeper" },
         { number: "30", name: "Miño", position: "goalkeeper" },
         { number: "1", name: "Ayala", position: "goalkeeper" },
         { number: "12", name: "Romero", position: "goalkeeper" },
         { number: "22", name: "Ávila", position: "defender" },
         { number: "6", name: "Laso", position: "defender" },
         { number: "32", name: "Almada", position: "defender" },
         { number: "14", name: "Novaretti", position: "defender" },
         { number: "3", name: "Blanco", position: "defender" },
         { number: "2", name: "Ferreyra", position: "defender" },
         { number: "13", name: "Mazzaco", position: "defender" },
         { number: "4", name: "Martínez", position: "defender" },
         { number: "20", name: "Torrent", position: "defender" },
         { number: "17", name: "Sangiovani", position: "defender" },
         { number: "21", name: "Rinaudo", position: "midfielder" },
         { number: "5", name: "Villagra", position: "midfielder" },
         { number: "16", name: "Tanlongo", position: "midfielder" },
         { number: "25", name: "Ojeda", position: "midfielder" },
         { number: "8", name: "Zabala", position: "midfielder" },
         { number: "10", name: "Vecchio", position: "midfielder" },
         { number: "18", name: "Lo Celso", position: "midfielder" },
         { number: "33", name: "Giaccone", position: "midfielder" },
         { number: "7", name: "Marinelli", position: "forward" },
         { number: "11", name: "Ferreyra", position: "forward" },
         { number: "27", name: "Infantino", position: "forward" },
         { number: "28", name: "Gamba", position: "forward" },
         { number: "-", name: "Cucchi", position: "forward" },
         { number: "9", name: "Ruben", position: "forward" },
         { number: "24", name: "Bonansea", position: "forward" },
         { number: "29", name: "Martínez Dupuy", position: "forward" },
         { number: "23", name: "Russo", position: "forward" },

      ]
   },
   {
      teamName: "sanlorenzo",
      players: [
         { number: "23", name: "Monetti", position: "goalkeeper" },
         { number: "12", name: "Torrico", position: "goalkeeper" },
         { number: "13", name: "López Kaleniuk", position: "goalkeeper" },
         { number: "25", name: "Devecchi", position: "goalkeeper" },
         { number: "30", name: "Flores", position: "defender" },
         { number: "6", name: "Gattoni", position: "defender" },
         { number: "2", name: "Donatti", position: "defender" },
         { number: "28", name: "Braghieri", position: "defender" },
         { number: "32", name: "Coloccini", position: "defender" },
         { number: "3", name: "Pittón", position: "defender" },
         { number: "22", name: "Rojas", position: "defender" },
         { number: "26", name: "Fernández Mercau", position: "defender" },
         { number: "24", name: "Herrera", position: "defender" },
         { number: "4", name: "Peruzzi", position: "defender" },
         { number: "29", name: "Salazar", position: "defender" },
         { number: "8", name: "Rodríguez", position: "midfielder" },
         { number: "-", name: "Gordillo", position: "midfielder" },
         { number: "5", name: "Menossi", position: "midfielder" },
         { number: "27", name: "Elías", position: "midfielder" },
         { number: "14", name: "Insaurralde", position: "midfielder" },
         { number: "20", name: "Ramírez", position: "midfielder" },
         { number: "10", name: "Ó. Romero", position: "midfielder" },
         { number: "34", name: "Palacios", position: "midfielder" },
         { number: "40", name: "Sabella", position: "midfielder" },
         { number: "11", name: "Á. Romero", position: "forward" },
         { number: "31", name: "Sequeira", position: "forward" },
         { number: "16", name: "Fernández", position: "forward" },
         { number: "33", name: "Díaz", position: "forward" },
         { number: "-", name: "Troyansky", position: "forward" },
         { number: "17", name: "Peralta Bauer", position: "forward" },
         { number: "7", name: "Melano", position: "forward" },
         { number: "9", name: "Di Santo", position: "forward" },
         { number: "19", name: "Hausch", position: "forward" },

      ]
   },
   {
      teamName: "talleres",
      players: [
         { number: "22", name: "Herrera", position: "goalkeeper" },
         { number: "1", name: "Díaz", position: "goalkeeper" },
         { number: "33", name: "Blázquez", position: "goalkeeper" },
         { number: "6", name: "Komar", position: "defender" },
         { number: "2", name: "Pérez", position: "defender" },
         { number: "4", name: "Hincapié", position: "defender" },
         { number: "39", name: "Paparelli", position: "defender" },
         { number: "15", name: "Díaz", position: "defender" },
         { number: "26", name: "Bersano", position: "defender" },
         { number: "14", name: "Tenaglia", position: "defender" },
         { number: "29", name: "Schott", position: "defender" },
         { number: "13", name: "Malatini", position: "defender" },
         { number: "5", name: "Navarro", position: "midfielder" },
         { number: "16", name: "Mac Allister", position: "midfielder" },
         { number: "27", name: "Torres", position: "midfielder" },
         { number: "8", name: "Méndez", position: "midfielder" },
         { number: "10", name: "Soñora", position: "midfielder" },
         { number: "17", name: "Álvez", position: "midfielder" },
         { number: "42", name: "Mamani", position: "forward" },
         { number: "7", name: "Valoyes", position: "forward" },
         { number: "20", name: "Fragapane", position: "forward" },
         { number: "28", name: "Auzqui", position: "forward" },
         { number: "77", name: "Guilherme Parede", position: "forward" },
         { number: "19", name: "Ortíz", position: "forward" },
         { number: "18", name: "Santos", position: "forward" },
         { number: "23", name: "Retegui", position: "forward" },
         { number: "38", name: "Córdoba", position: "forward" },
         { number: "9", name: "Cabral", position: "forward" },
         { number: "36", name: "Lago", position: "forward" },

      ]
   },
   {
      teamName: "union",
      players: [
         { number: "25", name: "Moyano", position: "goalkeeper" },
         { number: "35", name: "Bonansea", position: "goalkeeper" },
         { number: "27", name: "Galván", position: "defender" },
         { number: "6", name: "Nani", position: "defender" },
         { number: "17", name: "Blasi", position: "defender" },
         { number: "2", name: "Calderón", position: "defender" },
         { number: "24", name: "Godoy", position: "defender" },
         { number: "3", name: "Corvalán", position: "defender" },
         { number: "-", name: "Peñailillo", position: "defender" },
         { number: "28", name: "Portillo", position: "defender" },
         { number: "37", name: "Esquivel", position: "defender" },
         { number: "4", name: "Gerometta", position: "defender" },
         { number: "16", name: "Vera", position: "defender" },
         { number: "30", name: "Nardoni", position: "midfielder" },
         { number: "19", name: "Pittón", position: "midfielder" },
         { number: "5", name: "Acevedo", position: "midfielder" },
         { number: "14", name: "Leyes", position: "midfielder" },
         { number: "26", name: "Cañete", position: "midfielder" },
         { number: "21", name: "Comas", position: "midfielder" },
         { number: "34", name: "Zenón", position: "midfielder" },
         { number: "-", name: "Roldán", position: "midfielder" },
         { number: "45", name: "Palacio", position: "midfielder" },
         { number: "-", name: "Insaurralde", position: "forward" },
         { number: "32", name: "Borgnino", position: "forward" },
         { number: "23", name: "Luna Diale", position: "forward" },
         { number: "15", name: "González", position: "forward" },
         { number: "9", name: "Márquez", position: "forward" },
         { number: "11", name: "García", position: "forward" },
         { number: "44", name: "Juárez", position: "forward" },
         { number: "12", name: "Andereggen", position: "forward" },

      ]
   },
   {
      teamName: "velez",
      players: [
         { number: "12", name: "Hoyos", position: "goalkeeper" },
         { number: "22", name: "Domínguez", position: "goalkeeper" },
         { number: "40", name: "Borgogno", position: "goalkeeper" },
         { number: "29", name: "Abram", position: "defender" },
         { number: "17", name: "Giannetti", position: "defender" },
         { number: "2", name: "Amor", position: "defender" },
         { number: "-", name: "De los Santos", position: "defender" },
         { number: "28", name: "Brizuela", position: "defender" },
         { number: "5", name: "Ortega", position: "defender" },
         { number: "-", name: "Cavanagh", position: "defender" },
         { number: "24", name: "Guidara", position: "defender" },
         { number: "4", name: "De La Fuente", position: "defender" },
         { number: "-", name: "Cáseres", position: "midfielder" },
         { number: "27", name: "Galdames", position: "midfielder" },
         { number: "-", name: "Poblete", position: "midfielder" },
         { number: "15", name: "Mulet", position: "midfielder" },
         { number: "8", name: "Álvarez", position: "midfielder" },
         { number: "30", name: "Mancuello", position: "midfielder" },
         { number: "21", name: "Cáseres", position: "midfielder" },
         { number: "10", name: "Almada", position: "midfielder" },
         { number: "11", name: "Janson", position: "forward" },
         { number: "7", name: "Centurión", position: "forward" },
         { number: "14", name: "Orellano", position: "forward" },
         { number: "23", name: "Bouzat", position: "forward" },
         { number: "43", name: "Ramis", position: "forward" },
         { number: "18", name: "Tarragona", position: "forward" },
         { number: "19", name: "Lucero", position: "forward" },
         { number: "-", name: "Bazán", position: "forward" },
         { number: "9", name: "Monzón", position: "forward" },

      ]
   },
   {
      teamName: "platense",
      players: [
         { number: "34", name: "Ojeda", position: "goalkeeper" },
         { number: "1", name: "De Olivera", position: "goalkeeper" },
         { number: "23", name: "Desábato", position: "goalkeeper" },
         { number: "24", name: "Callegari", position: "defender" },
         { number: "6", name: "Recalde", position: "defender" },
         { number: "33", name: "Zalazar", position: "defender" },
         { number: "-", name: "Canuto", position: "defender" },
         { number: "2", name: "Iribarren", position: "defender" },
         { number: "3", name: "Infante", position: "defender" },
         { number: "21", name: "Lluy", position: "defender" },
         { number: "32", name: "Baldassarra", position: "midfielder" },
         { number: "20", name: "Palacios", position: "midfielder" },
         { number: "16", name: "Peréz", position: "midfielder" },
         { number: "14", name: "Bochi", position: "midfielder" },
         { number: "5", name: "Lamberti", position: "midfielder" },
         { number: "22", name: "Núñez", position: "midfielder" },
         { number: "8", name: "Bogado", position: "midfielder" },
         { number: "28", name: "Messidoro", position: "midfielder" },
         { number: "29", name: "Zeineddin", position: "forward" },
         { number: "10", name: "Schor", position: "forward" },
         { number: "35", name: "Bertolo", position: "forward" },
         { number: "11", name: "Sinisterra", position: "forward" },
         { number: "13", name: "Gerzel", position: "forward" },
         { number: "19", name: "Pereyra Díaz", position: "forward" },
         { number: "26", name: "Ilarregui", position: "forward" },
         { number: "-", name: "Susvielles", position: "forward" },
         { number: "25", name: "Curuchet", position: "forward" },
         { number: "9", name: "Vega", position: "forward" },

      ]
   },
   {
      teamName: "sarmiento",
      players: [
         { number: "1", name: "Vicentini", position: "goalkeeper" },
         { number: "-", name: "Daffonchio", position: "goalkeeper" },
         { number: "12", name: "Ferrero", position: "goalkeeper" },
         { number: "14", name: "Herrera", position: "defender" },
         { number: "18", name: "Salvareschi", position: "defender" },
         { number: "23", name: "Bazzana", position: "defender" },
         { number: "2", name: "Mancinelli", position: "defender" },
         { number: "20", name: "Antonini", position: "defender" },
         { number: "3", name: "Castet", position: "defender" },
         { number: "24", name: "Montoya", position: "defender" },
         { number: "15", name: "García", position: "defender" },
         { number: "-", name: "Molina", position: "defender" },
         { number: "4", name: "Garnier", position: "defender" },
         { number: "6", name: "Vismara", position: "midfielder" },
         { number: "37", name: "Caviglia", position: "midfielder" },
         { number: "8", name: "Pombo", position: "midfielder" },
         { number: "10", name: "Quiroga", position: "midfielder" },
         { number: "5", name: "Vázquez", position: "midfielder" },
         { number: "22", name: "Bravo", position: "midfielder" },
         { number: "30", name: "Montero", position: "midfielder" },
         { number: "7", name: "Graciani", position: "midfielder" },
         { number: "-", name: "Fornari", position: "midfielder" },
         { number: "17", name: "Alanís", position: "midfielder" },
         { number: "34", name: "Sánchez", position: "midfielder" },
         { number: "-", name: "Albertengo", position: "forward" },
         { number: "26", name: "Arismendi", position: "forward" },
         { number: "35", name: "Rincón", position: "forward" },
         { number: "31", name: "Borasi", position: "forward" },
         { number: "9", name: "Torres", position: "forward" },
         { number: "36", name: "É. Montaño", position: "forward" },
         { number: "11", name: "Vadalá", position: "forward" },
         { number: "21", name: "Brea", position: "forward" },

      ]
   },
]

export default teams