const teams = [
			 {
		teamName:"river",
		players:[
			{number:"1",name:"F. Armani",position:"goalkeeper"},
			{number:"25",name:"E. Bologna",position:"goalkeeper"},
			{number:"14",name:"G. Lux",position:"goalkeeper"},
			{number:"17",name:"P. Díaz",position:"defender"},
			{number:"6",name:"D. Martínez",position:"defender"},
			{number:"2",name:"R. Rojas",position:"defender"},
			{number:"28",name:"F. Biafore",position:"defender"},
			{number:"22",name:"J. Pinola",position:"defender"},
			{number:"4",name:"J. Maidana",position:"defender"},
			{number:"3",name:"F. Angileri",position:"defender"},
			{number:"20",name:"M. Casco",position:"defender"},
			{number:"16",name:"Vigo",position:"defender"},
			{number:"13",name:"E. Fernández",position:"midfielder"},
			{number:"5",name:"B. Zuculini",position:"midfielder"},
			{number:"24",name:"E. Pérez",position:"midfielder"},
			{number:"23",name:"L. Ponzio",position:"midfielder"},
			{number:"11",name:"N. Cruz",position:"midfielder"},
			{number:"26",name:"J. Paradela",position:"midfielder"},
			{number:"31",name:"S. Simón",position:"midfielder"},
			{number:"10",name:"J. Carrascal",position:"midfielder"},
			{number:"8",name:"A. Palavecino",position:"midfielder"},
			{number:"33",name:"T. Galván",position:"midfielder"},
			{number:"30",name:"B. Rollheiser",position:"forward"},
			{number:"9",name:"J. Álvarez",position:"forward"},
			{number:"19",name:"B. Romero",position:"forward"},
			{number:"7",name:"M. Suárez",position:"forward"},
			{number:"15",name:"F. Girotti",position:"forward"},
			{number:"27",name:"A. Fontana",position:"forward"},

			]
		},
	 {
		teamName:"boca",
		players:[
			{number:"1",name:"A. Rossi",position:"goalkeeper"},
			{number:"13",name:"J. García",position:"goalkeeper"},
			{number:"6",name:"M. Rojo",position:"defender"},
			{number:"24",name:"C. Izquierdoz",position:"defender"},
			{number:"2",name:"L. López",position:"defender"},
			{number:"5",name:"C. Zambrano",position:"defender"},
			{number:"18",name:"F. Fabra",position:"defender"},
			{number:"37",name:"A. Sández",position:"defender"},
			{number:"19",name:"V. Barco",position:"defender"},
			{number:"4",name:"M. Weigandt",position:"defender"},
			{number:"17",name:"L. Advíncula",position:"defender"},
			{number:"40",name:"E. Mancuso",position:"defender"},
			{number:"33",name:"A. Varela",position:"midfielder"},
			{number:"21",name:"J. Campuzano",position:"midfielder"},
			{number:"14",name:"E. Rolón",position:"midfielder"},
			{number:"36",name:"C. Medina",position:"midfielder"},
			{number:"32",name:"A. Almendra",position:"midfielder"},
			{number:"20",name:"J. Ramírez",position:"midfielder"},
			{number:"41",name:"R. Montes",position:"midfielder"},
			{number:"23",name:"D. González",position:"midfielder"},
			{number:"16",name:"A. Molinas",position:"midfielder"},
			{number:"8",name:"E. Cardona",position:"midfielder"},
			{number:"22",name:"S. Villa",position:"forward"},
			{number:"34",name:"A. Obando",position:"forward"},
			{number:"31",name:"C. Pavón",position:"forward"},
			{number:"30",name:"E. Zeballos",position:"forward"},
			{number:"11",name:"E. Salvio",position:"forward"},
			{number:"9",name:"N. Orsini",position:"forward"},
			{number:"29",name:"N. Briasco",position:"forward"},
			{number:"38",name:"L. Vázquez",position:"forward"},

			]
		},
	 {
		teamName:"velez",
		players:[
			{number:"12",name:"L. Hoyos",position:"goalkeeper"},
			{number:"22",name:"C. Lampe",position:"goalkeeper"},
			{number:"1",name:"M. Borgogno",position:"goalkeeper"},
			{number:"17",name:"L. Giannetti",position:"defender"},
			{number:"6",name:"M. Santos",position:"defender"},
			{number:"28",name:"M. Brizuela",position:"defender"},
			{number:"4",name:"E. Martínez",position:"defender"},
			{number:"34",name:"D. Fernández",position:"defender"},
			{number:"5",name:"F. Ortega",position:"defender"},
			{number:"46",name:"N. Romero",position:"defender"},
			{number:"24",name:"T. Guidara",position:"defender"},
			{number:"18",name:"L. Jara",position:"defender"},
			{number:"35",name:"S. Cáseres",position:"midfielder"},
			{number:"15",name:"A. Mulet",position:"midfielder"},
			{number:"16",name:"G. Poblete",position:"midfielder"},
			{number:"30",name:"F. Mancuello",position:"midfielder"},
			{number:"8",name:"R. Álvarez",position:"midfielder"},
			{number:"36",name:"N. Garayalde",position:"midfielder"},
			{number:"10",name:"T. Almada",position:"midfielder"},
			{number:"11",name:"L. Janson",position:"forward"},
			{number:"7",name:"R. Centurión",position:"forward"},
			{number:"14",name:"L. Orellano",position:"forward"},
			{number:"23",name:"A. Bouzat",position:"forward"},
			{number:"9",name:"C. Tarragona",position:"forward"},
			{number:"19",name:"J. Lucero",position:"forward"},
			{number:"21",name:"L. Pratto",position:"forward"},

			]
		},
	 {
		teamName:"lanus",
		players:[
			{number:"17",name:"L. Morales",position:"goalkeeper"},
			{number:"15",name:"L. Acosta",position:"goalkeeper"},
			{number:"3",name:"G. Burdisso",position:"defender"},
			{number:"6",name:"D. Braghieri",position:"defender"},
			{number:"29",name:"N. Thaller",position:"defender"},
			{number:"22",name:"M. Pérez",position:"defender"},
			{number:"25",name:"A. Bernabéi",position:"defender"},
			{number:"13",name:"J. Aude",position:"defender"},
			{number:"35",name:"B. Aguirre",position:"defender"},
			{number:"26",name:"L. Placido",position:"defender"},
			{number:"24",name:"N. Morgantini",position:"defender"},
			{number:"19",name:"J. Morel",position:"midfielder"},
			{number:"8",name:"T. Belmonte",position:"midfielder"},
			{number:"11",name:"M. Esquivel",position:"midfielder"},
			{number:"34",name:"F. Pérez",position:"midfielder"},
			{number:"38",name:"A. Rodríguez",position:"midfielder"},
			{number:"21",name:"F. Orozco",position:"forward"},
			{number:"7",name:"L. Acosta",position:"forward"},
			{number:"20",name:"I. Malcorra",position:"forward"},
			{number:"10",name:"P. Vega",position:"forward"},
			{number:"27",name:"Á. González",position:"forward"},
			{number:"42",name:"J. López",position:"forward"},
			{number:"9",name:"J. Sand",position:"forward"},

			]
		},
	 {
		teamName:"independiente",
		players:[
			{number:"1",name:"S. Sosa",position:"goalkeeper"},
			{number:"13",name:"M. Álvarez",position:"goalkeeper"},
			{number:"12",name:"R. Bacchia",position:"goalkeeper"},
			{number:"24",name:"S. Barreto",position:"defender"},
			{number:"2",name:"J. Laso",position:"defender"},
			{number:"33",name:"J. Insaurralde",position:"defender"},
			{number:"32",name:"A. Costa",position:"defender"},
			{number:"6",name:"E. Muñoz",position:"defender"},
			{number:"31",name:"P. Ostachuk",position:"defender"},
			{number:"3",name:"T. Ortega",position:"defender"},
			{number:"5",name:"L. Rodríguez",position:"defender"},
			{number:"16",name:"F. Bustos",position:"defender"},
			{number:"4",name:"G. Asís",position:"defender"},
			{number:"29",name:"L. Romero",position:"midfielder"},
			{number:"21",name:"C. Benavidez",position:"midfielder"},
			{number:"27",name:"J. Pacchini",position:"midfielder"},
			{number:"23",name:"D. Blanco",position:"midfielder"},
			{number:"15",name:"A. Soñora",position:"midfielder"},
			{number:"14",name:"L. González",position:"midfielder"},
			{number:"7",name:"A. Roa",position:"midfielder"},
			{number:"10",name:"A. Velasco",position:"forward"},
			{number:"11",name:"G. Togni",position:"forward"},
			{number:"30",name:"B. Martínez",position:"forward"},
			{number:"20",name:"R. Márquez",position:"forward"},
			{number:"18",name:"S. Romero",position:"forward"},
			{number:"9",name:"J. Herrera",position:"forward"},

			]
		},
	 {
		teamName:"talleres",
		players:[
			{number:"22",name:"G. Herrera",position:"goalkeeper"},
			{number:"33",name:"J. Blázquez",position:"goalkeeper"},
			{number:"2",name:"R. Pérez",position:"defender"},
			{number:"6",name:"J. Komar",position:"defender"},
			{number:"3",name:"J. Velázquez",position:"defender"},
			{number:"39",name:"R. Paparelli",position:"defender"},
			{number:"25",name:"F. Torres",position:"defender"},
			{number:"15",name:"E. Díaz",position:"defender"},
			{number:"21",name:"Á. Martino",position:"defender"},
			{number:"14",name:"N. Tenaglia",position:"defender"},
			{number:"13",name:"J. Malatini",position:"defender"},
			{number:"-",name:"S. Moyano",position:"defender"},
			{number:"18",name:"R. Villagra",position:"midfielder"},
			{number:"16",name:"F. Allister",position:"midfielder"},
			{number:"8",name:"J. Méndez",position:"midfielder"},
			{number:"26",name:"C. Villalba",position:"midfielder"},
			{number:"50",name:"D. García",position:"midfielder"},
			{number:"-",name:"F. Bersano",position:"midfielder"},
			{number:"10",name:"H. Fértoli",position:"forward"},
			{number:"7",name:"D. Valoyes",position:"forward"},
			{number:"28",name:"C. Auzqui",position:"forward"},
			{number:"77",name:"Parede",position:"forward"},
			{number:"19",name:"M. Ortiz",position:"forward"},
			{number:"11",name:"M. Sosa",position:"forward"},
			{number:"9",name:"M. Santos",position:"forward"},
			{number:"23",name:"M. Retegui",position:"forward"},
			{number:"20",name:"M. Córdoba",position:"forward"},
			{number:"30",name:"J. Esquivel",position:"forward"},

			]
		},
	 {
		teamName:"racing",
		players:[
			{number:"1",name:"G. Arias",position:"goalkeeper"},
			{number:"25",name:"G. Gómez",position:"goalkeeper"},
			{number:"13",name:"M. Tagliamonte",position:"goalkeeper"},
			{number:"30",name:"L. Sigali",position:"defender"},
			{number:"23",name:"N. Domínguez",position:"defender"},
			{number:"40",name:"J. Novillo",position:"defender"},
			{number:"6",name:"L. Orbán",position:"defender"},
			{number:"16",name:"M. Martínez",position:"defender"},
			{number:"12",name:"F. Prado",position:"defender"},
			{number:"5",name:"E. Mena",position:"defender"},
			{number:"3",name:"G. Cortez",position:"defender"},
			{number:"2",name:"J. Cáceres",position:"defender"},
			{number:"18",name:"E. Schelotto",position:"defender"},
			{number:"4",name:"I. Pillud",position:"defender"},
			{number:"29",name:"A. Moreno",position:"midfielder"},
			{number:"19",name:"L. Miranda",position:"midfielder"},
			{number:"26",name:"C. Alcaraz",position:"midfielder"},
			{number:"31",name:"M. Meli",position:"midfielder"},
			{number:"24",name:"J. López",position:"midfielder"},
			{number:"8",name:"F. Domínguez",position:"midfielder"},
			{number:"10",name:"M. Rojas",position:"midfielder"},
			{number:"34",name:"M. Lovera",position:"midfielder"},
			{number:"15",name:"I. Piatti",position:"midfielder"},
			{number:"28",name:"T. Chancalay",position:"forward"},
			{number:"17",name:"B. Garré",position:"forward"},
			{number:"9",name:"E. Copetti",position:"forward"},
			{number:"43",name:"G. Viera",position:"forward"},
			{number:"27",name:"J. Correa",position:"forward"},
			{number:"15",name:"L. López",position:"forward"},
			{number:"20",name:"D. Cvitanich",position:"forward"},
			{number:"44",name:"I. Maggi",position:"forward"},

			]
		},
	 {
		teamName:"colon",
		players:[
			{number:"1",name:"L. Burián",position:"goalkeeper"},
			{number:"17",name:"I. Chicco",position:"goalkeeper"},
			{number:"22",name:"J. Hass",position:"goalkeeper"},
			{number:"33",name:"F. Garcés",position:"defender"},
			{number:"40",name:"R. Delgado",position:"defender"},
			{number:"3",name:"G. Piovi",position:"defender"},
			{number:"6",name:"P. Goltz",position:"defender"},
			{number:"2",name:"B. Bianchi",position:"defender"},
			{number:"24",name:"N. Gallardo",position:"defender"},
			{number:"4",name:"F. Mura",position:"defender"},
			{number:"21",name:"Meza",position:"defender"},
			{number:"14",name:"F. Lértora",position:"midfielder"},
			{number:"5",name:"T. Moschión",position:"midfielder"},
			{number:"29",name:"R. Aliendro",position:"midfielder"},
			{number:"16",name:"C. Ferreira",position:"midfielder"},
			{number:"11",name:"A. Castro",position:"midfielder"},
			{number:"8",name:"Y. Góez",position:"midfielder"},
			{number:"35",name:"F. Farías",position:"midfielder"},
			{number:"7",name:"M. Formica",position:"midfielder"},
			{number:"30",name:"S. Pierotti",position:"forward"},
			{number:"23",name:"C. Bernardi",position:"forward"},
			{number:"18",name:"N. Leguizamón",position:"forward"},
			{number:"9",name:"L. Beltrán",position:"forward"},
			{number:"19",name:"W. Morelo",position:"forward"},

			]
		},
	 {
		teamName:"estudiantes",
		players:[
			{number:"21",name:"M. Andújar",position:"goalkeeper"},
			{number:"1",name:"J. Pourtau",position:"goalkeeper"},
			{number:"12",name:"E. González",position:"goalkeeper"},
			{number:"3",name:"A. Rogel",position:"defender"},
			{number:"18",name:"F. Noguera",position:"defender"},
			{number:"2",name:"F. Tobio",position:"defender"},
			{number:"4",name:"M. Guzmán",position:"defender"},
			{number:"14",name:"J. Miño",position:"defender"},
			{number:"15",name:"N. Pasquini",position:"defender"},
			{number:"29",name:"L. Godoy",position:"defender"},
			{number:"13",name:"M. Aguirregaray",position:"defender"},
			{number:"28",name:"F. Zapiola",position:"midfielder"},
			{number:"30",name:"J. Rodríguez",position:"midfielder"},
			{number:"5",name:"D. Ayala",position:"midfielder"},
			{number:"20",name:"B. Kociubinski",position:"midfielder"},
			{number:"8",name:"F. Zuqui",position:"midfielder"},
			{number:"11",name:"D. Verón",position:"midfielder"},
			{number:"17",name:"M. Castro",position:"midfielder"},
			{number:"27",name:"N. Palavecino",position:"midfielder"},
			{number:"7",name:"M. Pellegrini",position:"forward"},
			{number:"31",name:"R. Ramírez",position:"forward"},
			{number:"16",name:"F. Apaolaza",position:"forward"},
			{number:"9",name:"L. Díaz",position:"forward"},
			{number:"10",name:"G. Prete",position:"forward"},
			{number:"19",name:"J. Ayoví",position:"forward"},

			]
		},
	 {
		teamName:"argentinos",
		players:[
			{number:"12",name:"L. Chaves",position:"goalkeeper"},
			{number:"20",name:"F. Lanzillotta",position:"goalkeeper"},
			{number:"1",name:"L. Finochietto",position:"goalkeeper"},
			{number:"2",name:"M. Torrén",position:"defender"},
			{number:"16",name:"C. Quintana",position:"defender"},
			{number:"29",name:"M. Cesare",position:"defender"},
			{number:"14",name:"L. Mosevich",position:"defender"},
			{number:"30",name:"P. Minissale",position:"defender"},
			{number:"24",name:"E. Gómez",position:"defender"},
			{number:"6",name:"L. Villalba",position:"defender"},
			{number:"4",name:"K. Allister",position:"defender"},
			{number:"19",name:"L. Gómez",position:"defender"},
			{number:"15",name:"J. Sandoval",position:"defender"},
			{number:"5",name:"F. Vera",position:"midfielder"},
			{number:"17",name:"F. Moyano",position:"midfielder"},
			{number:"14",name:"E. Kalinski",position:"midfielder"},
			{number:"18",name:"D. Sosa",position:"midfielder"},
			{number:"10",name:"G. Florentín",position:"midfielder"},
			{number:"11",name:"J. Gómez",position:"midfielder"},
			{number:"8",name:"G. Carabajal",position:"midfielder"},
			{number:"25",name:"M. Coronel",position:"midfielder"},
			{number:"7",name:"J. Cabrera",position:"forward"},
			{number:"26",name:"M. Romero",position:"forward"},
			{number:"32",name:"N. Reniero",position:"forward"},
			{number:"9",name:"G. Ávalos",position:"forward"},
			{number:"28",name:"E. Herrera",position:"forward"},

			]
		},
	 {
		teamName:"sanlorenzo",
		players:[
			{number:"17",name:"A. Batalla",position:"goalkeeper"},
			{number:"12",name:"S. Torrico",position:"goalkeeper"},
			{number:"32",name:"F. Flores",position:"defender"},
			{number:"6",name:"F. Gattoni",position:"defender"},
			{number:"2",name:"A. Donatti",position:"defender"},
			{number:"3",name:"C. Zapata",position:"defender"},
			{number:"14",name:"B. Pittón",position:"defender"},
			{number:"22",name:"G. Rojas",position:"defender"},
			{number:"26",name:"N. Mercau",position:"defender"},
			{number:"4",name:"M. Herrera",position:"defender"},
			{number:"30",name:"G. Peruzzi",position:"defender"},
			{number:"5",name:"Y. Gordillo",position:"midfielder"},
			{number:"38",name:"S. Rosané",position:"midfielder"},
			{number:"20",name:"N. Ortigoza",position:"midfielder"},
			{number:"27",name:"J. Elías",position:"midfielder"},
			{number:"18",name:"A. Bauer",position:"midfielder"},
			{number:"40",name:"A. Sabella",position:"midfielder"},
			{number:"34",name:"J. Palacios",position:"midfielder"},
			{number:"42",name:"A. Martegani",position:"midfielder"},
			{number:"28",name:"N. Barrios",position:"forward"},
			{number:"7",name:"E. Cerutti",position:"forward"},
			{number:"29",name:"N. Fernández",position:"forward"},
			{number:"33",name:"A. Díaz",position:"forward"},
			{number:"23",name:"M. Bauer",position:"forward"},
			{number:"9",name:"F. Santo",position:"forward"},
			{number:"19",name:"A. Hausch",position:"forward"},

			]
		},
	 {
		teamName:"defensa",
		players:[
			{number:"22",name:"E. Unsain",position:"goalkeeper"},
			{number:"1",name:"M. Ledesma",position:"goalkeeper"},
			{number:"36",name:"L. Amadé",position:"goalkeeper"},
			{number:"2",name:"A. Frías",position:"defender"},
			{number:"4",name:"F. Paredes",position:"defender"},
			{number:"25",name:"T. Cardona",position:"defender"},
			{number:"28",name:"J. Rodríguez",position:"defender"},
			{number:"6",name:"N. Colombo",position:"defender"},
			{number:"13",name:"A. Soto",position:"defender"},
			{number:"3",name:"M. Benítez",position:"defender"},
			{number:"14",name:"N. Tripichio",position:"defender"},
			{number:"15",name:"M. Rodríguez",position:"defender"},
			{number:"27",name:"H. Silva",position:"defender"},
			{number:"31",name:"K. Gutiérrez",position:"midfielder"},
			{number:"30",name:"R. Loaiza",position:"midfielder"},
			{number:"23",name:"B. Rivero",position:"midfielder"},
			{number:"35",name:"A. Maíz",position:"midfielder"},
			{number:"16",name:"T. Escalante",position:"midfielder"},
			{number:"10",name:"T. Martínez",position:"midfielder"},
			{number:"18",name:"T. Ortiz",position:"midfielder"},
			{number:"32",name:"M. Luayza",position:"midfielder"},
			{number:"29",name:"F. Pizzini",position:"forward"},
			{number:"11",name:"C. Rotondi",position:"forward"},
			{number:"24",name:"H. Fernández",position:"forward"},
			{number:"-",name:"N. Maná",position:"forward"},
			{number:"7",name:"W. Bou",position:"forward"},
			{number:"9",name:"M. Merentiel",position:"forward"},
			{number:"33",name:"R. Contreras",position:"forward"},
			{number:"19",name:"G. Hachen",position:"forward"},
			{number:"8",name:"L. Barrios",position:"forward"},

			]
		},
	 {
		teamName:"newells",
		players:[
			{number:"1",name:"A. Aguerre",position:"goalkeeper"},
			{number:"12",name:"R. Macagno",position:"goalkeeper"},
			{number:"23",name:"W. Barlasina",position:"goalkeeper"},
			{number:"2",name:"C. Lema",position:"defender"},
			{number:"6",name:"J. Canale",position:"defender"},
			{number:"19",name:"F. Mansilla",position:"defender"},
			{number:"22",name:"M. Capasso",position:"defender"},
			{number:"28",name:"M. Bíttolo",position:"defender"},
			{number:"38",name:"F. Negri",position:"defender"},
			{number:"4",name:"F. Escobar",position:"defender"},
			{number:"50",name:"P. Acevedo",position:"defender"},
			{number:"13",name:"J. Sforza",position:"midfielder"},
			{number:"20",name:"J. Fernández",position:"midfielder"},
			{number:"15",name:"D. Calcaterra",position:"midfielder"},
			{number:"30",name:"M. Maccari",position:"midfielder"},
			{number:"31",name:"J. Cacciabue",position:"midfielder"},
			{number:"8",name:"P. Pérez",position:"midfielder"},
			{number:"5",name:"F. Belluschi",position:"midfielder"},
			{number:"27",name:"G. Compagnucci",position:"midfielder"},
			{number:"36",name:"N. Castro",position:"midfielder"},
			{number:"21",name:"D. Rodríguez",position:"midfielder"},
			{number:"24",name:"J. Garro",position:"forward"},
			{number:"44",name:"F. González",position:"forward"},
			{number:"26",name:"R. Sordo",position:"forward"},
			{number:"11",name:"M. Rodríguez",position:"forward"},
			{number:"33",name:"M. Comba",position:"forward"},
			{number:"7",name:"L. Cingolani",position:"forward"},
			{number:"17",name:"J. Giani",position:"forward"},
			{number:"9",name:"J. Cristaldo",position:"forward"},
			{number:"32",name:"I. Scocco",position:"forward"},
			{number:"18",name:"P. Sabbag",position:"forward"},

			]
		},
	 {
		teamName:"banfield",
		players:[
			{number:"1",name:"F. Altamirano",position:"goalkeeper"},
			{number:"21",name:"F. Cambeses",position:"goalkeeper"},
			{number:"26",name:"G. Tanco",position:"defender"},
			{number:"2",name:"A. Maldonado",position:"defender"},
			{number:"6",name:"L. Lollo",position:"defender"},
			{number:"19",name:"A. Sosa",position:"defender"},
			{number:"17",name:"G. Canto",position:"defender"},
			{number:"3",name:"F. Quinteros",position:"defender"},
			{number:"32",name:"E. Coronel",position:"defender"},
			{number:"24",name:"L. Flores",position:"defender"},
			{number:"25",name:"A. Cabrera",position:"midfielder"},
			{number:"15",name:"L. Ríos",position:"midfielder"},
			{number:"14",name:"G. Miceli",position:"midfielder"},
			{number:"5",name:"N. Linares",position:"midfielder"},
			{number:"27",name:"N. Domingo",position:"midfielder"},
			{number:"8",name:"G. Galoppo",position:"midfielder"},
			{number:"28",name:"M. González",position:"midfielder"},
			{number:"30",name:"V. Barbero",position:"midfielder"},
			{number:"20",name:"J. Soñora",position:"midfielder"},
			{number:"10",name:"J. Dátolo",position:"midfielder"},
			{number:"11",name:"A. Urzi",position:"forward"},
			{number:"22",name:"J. Álvarez",position:"forward"},
			{number:"7",name:"M. Cuero",position:"forward"},
			{number:"9",name:"J. Cruz",position:"forward"},
			{number:"18",name:"R. Enrique",position:"forward"},
			{number:"29",name:"L. Pons",position:"forward"},

			]
		},
	 {
		teamName:"godoycruz",
		players:[
			{number:"12",name:"J. Espínola",position:"goalkeeper"},
			{number:"1",name:"R. Ramírez",position:"goalkeeper"},
			{number:"23",name:"N. Ibáñez",position:"goalkeeper"},
			{number:"24",name:"G. Ortiz",position:"defender"},
			{number:"22",name:"G. Ferrari",position:"defender"},
			{number:"2",name:"N. Sánchez",position:"defender"},
			{number:"37",name:"A. Aguirre",position:"defender"},
			{number:"26",name:"D. Pérez",position:"defender"},
			{number:"3",name:"L. González",position:"defender"},
			{number:"6",name:"I. Escobar",position:"defender"},
			{number:"28",name:"E. López",position:"defender"},
			{number:"25",name:"N. Breitenbruch",position:"defender"},
			{number:"19",name:"M. Llano",position:"defender"},
			{number:"5",name:"N. Acevedo",position:"midfielder"},
			{number:"4",name:"E. Cirigliano",position:"midfielder"},
			{number:"8",name:"L. Pizarro",position:"midfielder"},
			{number:"36",name:"B. Leyes",position:"midfielder"},
			{number:"31",name:"A. Álvarez",position:"midfielder"},
			{number:"32",name:"G. Abrego",position:"midfielder"},
			{number:"34",name:"G. Pereira",position:"midfielder"},
			{number:"10",name:"V. Burgoa",position:"midfielder"},
			{number:"11",name:"M. Ojeda",position:"forward"},
			{number:"7",name:"J. Chalá",position:"forward"},
			{number:"77",name:"M. González",position:"forward"},
			{number:"33",name:"E. Bullaude",position:"forward"},
			{number:"16",name:"M. Ramírez",position:"forward"},
			{number:"9",name:"T. Badaloni",position:"forward"},
			{number:"27",name:"S. Lomónaco",position:"forward"},
			{number:"17",name:"C. Colmán",position:"forward"},
			{number:"20",name:"A. Cantero",position:"forward"},

			]
		},
	 {
		teamName:"central",
		players:[
			{number:"19",name:"J. Broun",position:"goalkeeper"},
			{number:"12",name:"J. Romero",position:"goalkeeper"},
			{number:"1",name:"J. Ayala",position:"goalkeeper"},
			{number:"22",name:"G. Ávila",position:"defender"},
			{number:"32",name:"F. Almada",position:"defender"},
			{number:"2",name:"N. Ferreyra",position:"defender"},
			{number:"48",name:"R. Garay",position:"defender"},
			{number:"3",name:"L. Blanco",position:"defender"},
			{number:"26",name:"N. Franco",position:"defender"},
			{number:"4",name:"D. Martínez",position:"defender"},
			{number:"20",name:"F. Torrent",position:"defender"},
			{number:"14",name:"R. Sangiovani",position:"defender"},
			{number:"25",name:"E. Ojeda",position:"midfielder"},
			{number:"6",name:"L. Desábato",position:"midfielder"},
			{number:"21",name:"F. Rinaudo",position:"midfielder"},
			{number:"41",name:"J. Luques",position:"midfielder"},
			{number:"15",name:"M. Rabuñal",position:"midfielder"},
			{number:"10",name:"E. Vecchio",position:"midfielder"},
			{number:"18",name:"F. Celso",position:"midfielder"},
			{number:"30",name:"M. Covea",position:"midfielder"},
			{number:"7",name:"A. Marinelli",position:"forward"},
			{number:"11",name:"L. Ferreyra",position:"forward"},
			{number:"27",name:"G. Infantino",position:"forward"},
			{number:"8",name:"D. Zabala",position:"forward"},
			{number:"17",name:"M. Caraglio",position:"forward"},
			{number:"28",name:"L. Gamba",position:"forward"},
			{number:"29",name:"L. Dupuy",position:"forward"},
			{number:"9",name:"M. Ruben",position:"forward"},
			{number:"23",name:"I. Russo",position:"forward"},

			]
		},
	 {
		teamName:"huracan",
		players:[
			{number:"1",name:"M. Díaz",position:"goalkeeper"},
			{number:"32",name:"S. Meza",position:"goalkeeper"},
			{number:"27",name:"R. Ferrario",position:"goalkeeper"},
			{number:"6",name:"L. Merolla",position:"defender"},
			{number:"34",name:"J. Galván",position:"defender"},
			{number:"2",name:"J. Moya",position:"defender"},
			{number:"13",name:"W. Pérez",position:"defender"},
			{number:"46",name:"I. Erquiaga",position:"defender"},
			{number:"25",name:"C. Ibáñez",position:"defender"},
			{number:"3",name:"L. Grimi",position:"defender"},
			{number:"4",name:"R. Lozano",position:"defender"},
			{number:"35",name:"I. Quílez",position:"defender"},
			{number:"8",name:"C. Yacob",position:"midfielder"},
			{number:"15",name:"F. Marín",position:"midfielder"},
			{number:"30",name:"D. Mercado",position:"midfielder"},
			{number:"23",name:"L. Vera",position:"midfielder"},
			{number:"10",name:"F. Cristaldo",position:"midfielder"},
			{number:"5",name:"S. Hezze",position:"midfielder"},
			{number:"28",name:"F. Henríquez",position:"midfielder"},
			{number:"18",name:"P. Toranzo",position:"midfielder"},
			{number:"24",name:"N. Silva",position:"forward"},
			{number:"11",name:"J. Acevedo",position:"forward"},
			{number:"16",name:"R. Cabral",position:"forward"},
			{number:"19",name:"S. Rincón",position:"forward"},
			{number:"12",name:"S. Ramírez",position:"forward"},
			{number:"20",name:"J. Candia",position:"forward"},
			{number:"9",name:"E. Triverio",position:"forward"},
			{number:"7",name:"M. Cóccaro",position:"forward"},

			]
		},
	 {
		teamName:"gimnasia",
		players:[
			{number:"17",name:"R. Rey",position:"goalkeeper"},
			{number:"1",name:"T. Durso",position:"goalkeeper"},
			{number:"12",name:"N. Insfrán",position:"goalkeeper"},
			{number:"24",name:"G. Guiffrey",position:"defender"},
			{number:"2",name:"G. Fratta",position:"defender"},
			{number:"23",name:"M. Coronel",position:"defender"},
			{number:"28",name:"T. Fernández",position:"defender"},
			{number:"35",name:"B. Palazzo",position:"defender"},
			{number:"32",name:"M. Melluso",position:"defender"},
			{number:"25",name:"L. Licht",position:"defender"},
			{number:"16",name:"F. Gerometta",position:"defender"},
			{number:"4",name:"L. Morales",position:"defender"},
			{number:"15",name:"H. Mancilla",position:"midfielder"},
			{number:"33",name:"N. Leyes",position:"midfielder"},
			{number:"19",name:"E. Jara",position:"midfielder"},
			{number:"27",name:"M. Insaurralde",position:"midfielder"},
			{number:"5",name:"E. Cecchini",position:"midfielder"},
			{number:"22",name:"M. Miranda",position:"midfielder"},
			{number:"10",name:"B. Alemán",position:"midfielder"},
			{number:"18",name:"N. Colazo",position:"midfielder"},
			{number:"11",name:"M. García",position:"midfielder"},
			{number:"21",name:"L. Chávez",position:"midfielder"},
			{number:"26",name:"F. Torres",position:"forward"},
			{number:"7",name:"J. Carbonero",position:"forward"},
			{number:"43",name:"E. Ramírez",position:"forward"},
			{number:"8",name:"L. Rodríguez",position:"forward"},
			{number:"9",name:"N. Contin",position:"forward"},
			{number:"30",name:"R. Holgado",position:"forward"},
			{number:"37",name:"S. Cocimano",position:"forward"},
			{number:"39",name:"A. Domínguez",position:"forward"},

			]
		},
	 {
		teamName:"atltucuman",
		players:[
			{number:"17",name:"T. Marchiori",position:"goalkeeper"},
			{number:"1",name:"C. Lucchetti",position:"goalkeeper"},
			{number:"15",name:"Y. Cabral",position:"defender"},
			{number:"6",name:"M. Osores",position:"defender"},
			{number:"27",name:"S. Vergini",position:"defender"},
			{number:"20",name:"N. Romero",position:"defender"},
			{number:"25",name:"C. Albornoz",position:"defender"},
			{number:"30",name:"G. Patrón",position:"defender"},
			{number:"39",name:"M. Orihuela",position:"defender"},
			{number:"2",name:"M. Ortiz",position:"defender"},
			{number:"4",name:"F. Campos",position:"defender"},
			{number:"-",name:"G. Toledo",position:"defender"},
			{number:"14",name:"A. Lagos",position:"defender"},
			{number:"7",name:"F. Mussis",position:"midfielder"},
			{number:"5",name:"A. Bustos",position:"midfielder"},
			{number:"21",name:"C. Erbes",position:"midfielder"},
			{number:"22",name:"J. Pereyra",position:"midfielder"},
			{number:"23",name:"R. Carrera",position:"midfielder"},
			{number:"8",name:"G. Acosta",position:"midfielder"},
			{number:"19",name:"E. Rosales",position:"midfielder"},
			{number:"10",name:"L. Heredia",position:"midfielder"},
			{number:"26",name:"O. Benítez",position:"forward"},
			{number:"29",name:"K. Luna",position:"forward"},
			{number:"12",name:"Rius",position:"forward"},
			{number:"24",name:"R. Tesuri",position:"forward"},
			{number:"16",name:"N. Laméndola",position:"forward"},
			{number:"9",name:"A. Lotti",position:"forward"},
			{number:"11",name:"C. Menéndez",position:"forward"},
			{number:"18",name:"R. Ruiz",position:"forward"},

			]
		},
	 {
		teamName:"union",
		players:[
			{number:"25",name:"S. Moyano",position:"goalkeeper"},
			{number:"35",name:"F. Bonansea",position:"goalkeeper"},
			{number:"2",name:"F. Calderón",position:"defender"},
			{number:"28",name:"J. Portillo",position:"defender"},
			{number:"17",name:"B. Blasi",position:"defender"},
			{number:"6",name:"D. Gissi",position:"defender"},
			{number:"3",name:"C. Corvalán",position:"defender"},
			{number:"18",name:"N. Peñailillo",position:"defender"},
			{number:"37",name:"L. Esquivel",position:"defender"},
			{number:"22",name:"E. Brítez",position:"defender"},
			{number:"16",name:"F. Vera",position:"defender"},
			{number:"30",name:"J. Nardoni",position:"midfielder"},
			{number:"19",name:"M. Pittón",position:"midfielder"},
			{number:"10",name:"M. Cañete",position:"midfielder"},
			{number:"21",name:"G. Comas",position:"midfielder"},
			{number:"8",name:"E. Roldán",position:"midfielder"},
			{number:"39",name:"I. Machuca",position:"midfielder"},
			{number:"7",name:"C. Insaurralde",position:"forward"},
			{number:"32",name:"M. Borgnino",position:"forward"},
			{number:"15",name:"G. González",position:"forward"},
			{number:"23",name:"M. Diale",position:"forward"},
			{number:"34",name:"K. Zenón",position:"forward"},
			{number:"20",name:"N. Cordero",position:"forward"},
			{number:"9",name:"F. Márquez",position:"forward"},
			{number:"11",name:"J. García",position:"forward"},
			{number:"27",name:"N. Blandi",position:"forward"},
			{number:"29",name:"D. Juárez",position:"forward"},

			]
		},
	 {
		teamName:"centralcordoba",
		players:[
			{number:"32",name:"A. Mehring",position:"goalkeeper"},
			{number:"23",name:"C. Rigamonti",position:"goalkeeper"},
			{number:"13",name:"C. Taborda",position:"goalkeeper"},
			{number:"4",name:"O. Salomón",position:"defender"},
			{number:"44",name:"A. Maciel",position:"defender"},
			{number:"2",name:"F. Andueza",position:"defender"},
			{number:"20",name:"D. Rentería",position:"defender"},
			{number:"6",name:"F. Sbuttoni",position:"defender"},
			{number:"12",name:"J. Bay",position:"defender"},
			{number:"3",name:"N. Banegas",position:"defender"},
			{number:"25",name:"G. Bettini",position:"defender"},
			{number:"8",name:"J. González",position:"defender"},
			{number:"34",name:"L. Arzamendia",position:"defender"},
			{number:"5",name:"C. Vega",position:"midfielder"},
			{number:"14",name:"J. Galeano",position:"midfielder"},
			{number:"18",name:"J. Soraire",position:"midfielder"},
			{number:"19",name:"L. Torres",position:"midfielder"},
			{number:"39",name:"M. Montenegro",position:"midfielder"},
			{number:"24",name:"M. Mier",position:"midfielder"},
			{number:"22",name:"A. Martínez",position:"midfielder"},
			{number:"27",name:"C. Lattanzio",position:"forward"},
			{number:"7",name:"L. Sequeira",position:"forward"},
			{number:"21",name:"L. Brochero",position:"forward"},
			{number:"10",name:"H. López",position:"forward"},
			{number:"45",name:"M. Giménez",position:"forward"},
			{number:"16",name:"L. Melano",position:"forward"},
			{number:"28",name:"A. Argañaraz",position:"forward"},
			{number:"11",name:"S. Ribas",position:"forward"},
			{number:"9",name:"C. Riaño",position:"forward"},

			]
		},
	 {
		teamName:"aldosivi",
		players:[
			{number:"25",name:"J. Devecchi",position:"goalkeeper"},
			{number:"35",name:"F. Assmann",position:"goalkeeper"},
			{number:"1",name:"L. Pocrnjic",position:"goalkeeper"},
			{number:"26",name:"E. Insúa",position:"defender"},
			{number:"2",name:"M. Quintana",position:"defender"},
			{number:"6",name:"F. Coloccini",position:"defender"},
			{number:"19",name:"M. Miers",position:"defender"},
			{number:"28",name:"F. Román",position:"defender"},
			{number:"13",name:"E. Insúa",position:"defender"},
			{number:"14",name:"F. Milo",position:"defender"},
			{number:"21",name:"E. Iñiguez",position:"defender"},
			{number:"4",name:"R. Lucero",position:"defender"},
			{number:"5",name:"G. Romero",position:"midfielder"},
			{number:"24",name:"G. Lodico",position:"midfielder"},
			{number:"10",name:"F. Grahl",position:"midfielder"},
			{number:"12",name:"F. Gino",position:"midfielder"},
			{number:"33",name:"L. Maciel",position:"midfielder"},
			{number:"36",name:"J. Indacoechea",position:"midfielder"},
			{number:"18",name:"F. Cerro",position:"midfielder"},
			{number:"32",name:"P. Becker",position:"midfielder"},
			{number:"17",name:"F. Perinciolo",position:"midfielder"},
			{number:"20",name:"M. Braida",position:"forward"},
			{number:"8",name:"J. Iritier",position:"forward"},
			{number:"16",name:"J. Zacaría",position:"forward"},
			{number:"23",name:"L. Guzmán",position:"forward"},
			{number:"77",name:"M. Cauteruccio",position:"forward"},
			{number:"7",name:"F. Andrada",position:"forward"},
			{number:"15",name:"G. Hauche",position:"forward"},
			{number:"11",name:"L. Rinaldi",position:"forward"},
			{number:"22",name:"G. Aranda",position:"forward"},
			{number:"29",name:"U. Ramírez",position:"forward"},

			]
		},
	 {
		teamName:"platense",
		players:[
			{number:"22",name:"L. Ojeda",position:"goalkeeper"},
			{number:"1",name:"J. Olivera",position:"goalkeeper"},
			{number:"23",name:"A. Desábato",position:"goalkeeper"},
			{number:"30",name:"F. Cardozo",position:"defender"},
			{number:"38",name:"K. Lomónaco",position:"defender"},
			{number:"6",name:"L. Recalde",position:"defender"},
			{number:"24",name:"S. Callegari",position:"defender"},
			{number:"32",name:"L. Acevedo",position:"defender"},
			{number:"2",name:"N. Iribarren",position:"defender"},
			{number:"3",name:"J. Infante",position:"defender"},
			{number:"4",name:"A. Schott",position:"defender"},
			{number:"17",name:"C. Marcial",position:"defender"},
			{number:"11",name:"F. Russo",position:"midfielder"},
			{number:"21",name:"I. Gómez",position:"midfielder"},
			{number:"5",name:"H. Lamberti",position:"midfielder"},
			{number:"14",name:"R. Bochi",position:"midfielder"},
			{number:"10",name:"F. Baldassarra",position:"midfielder"},
			{number:"8",name:"M. Bogado",position:"midfielder"},
			{number:"-",name:"J. Colorado",position:"midfielder"},
			{number:"20",name:"T. Palacios",position:"midfielder"},
			{number:"9",name:"B. Mansilla",position:"forward"},
			{number:"26",name:"I. Schor",position:"forward"},
			{number:"35",name:"N. Bertolo",position:"forward"},
			{number:"18",name:"H. Tijanovich",position:"forward"},
			{number:"13",name:"G. Gerzel",position:"forward"},
			{number:"28",name:"J. Marcioni",position:"forward"},
			{number:"7",name:"M. Tissera",position:"forward"},
			{number:"39",name:"T. Sandoval",position:"forward"},
			{number:"25",name:"F. Curuchet",position:"forward"},
			{number:"37",name:"F. Monzón",position:"forward"},

			]
		},
	 {
		teamName:"patronato",
		players:[
			{number:"12",name:"M. Ibáñez",position:"goalkeeper"},
			{number:"34",name:"M. Mansilla",position:"goalkeeper"},
			{number:"1",name:"F. Rivasseau",position:"goalkeeper"},
			{number:"3",name:"O. Benítez",position:"defender"},
			{number:"66",name:"S. Ojeda",position:"defender"},
			{number:"14",name:"H. Magallanes",position:"defender"},
			{number:"22",name:"R. Guerreño",position:"defender"},
			{number:"30",name:"L. Kruspzky",position:"defender"},
			{number:"28",name:"F. Cobos",position:"defender"},
			{number:"23",name:"B. Urribarri",position:"defender"},
			{number:"5",name:"L. Marín",position:"defender"},
			{number:"4",name:"L. Geminiani",position:"defender"},
			{number:"32",name:"F. Leys",position:"midfielder"},
			{number:"13",name:"B. Nievas",position:"midfielder"},
			{number:"24",name:"D. Lemos",position:"midfielder"},
			{number:"7",name:"H. Canteros",position:"midfielder"},
			{number:"6",name:"T. Banega",position:"midfielder"},
			{number:"15",name:"F. Vázquez",position:"midfielder"},
			{number:"29",name:"M. Palavecino",position:"midfielder"},
			{number:"11",name:"N. Delgadillo",position:"forward"},
			{number:"37",name:"F. Dettler",position:"forward"},
			{number:"10",name:"L. Comas",position:"forward"},
			{number:"25",name:"A. Pastorelli",position:"forward"},
			{number:"8",name:"G. Gudiño",position:"forward"},
			{number:"21",name:"M. Garay",position:"forward"},
			{number:"33",name:"M. Pardo",position:"forward"},
			{number:"18",name:"N. Albarracín",position:"forward"},
			{number:"36",name:"N. Bandiera",position:"forward"},
			{number:"9",name:"S. Sánchez",position:"forward"},
			{number:"20",name:"J. Arias",position:"forward"},
			{number:"19",name:"N. Franco",position:"forward"},

			]
		},
	 {
		teamName:"sarmiento",
		players:[
			{number:"1",name:"M. Vicentini",position:"goalkeeper"},
			{number:"12",name:"F. Ferrero",position:"goalkeeper"},
			{number:"18",name:"B. Salvareschi",position:"defender"},
			{number:"74",name:"G. Sauro",position:"defender"},
			{number:"23",name:"N. Bazzana",position:"defender"},
			{number:"35",name:"F. Rasmussen",position:"defender"},
			{number:"2",name:"F. Mancinelli",position:"defender"},
			{number:"3",name:"F. Castet",position:"defender"},
			{number:"24",name:"L. Montoya",position:"defender"},
			{number:"15",name:"M. García",position:"defender"},
			{number:"25",name:"M. Molina",position:"defender"},
			{number:"4",name:"L. Garnier",position:"defender"},
			{number:"39",name:"F. Paradela",position:"midfielder"},
			{number:"29",name:"M. García",position:"midfielder"},
			{number:"5",name:"J. Chicco",position:"midfielder"},
			{number:"6",name:"F. Vismara",position:"midfielder"},
			{number:"10",name:"S. Quiroga",position:"midfielder"},
			{number:"8",name:"C. Pombo",position:"midfielder"},
			{number:"22",name:"F. Bravo",position:"midfielder"},
			{number:"7",name:"G. Graciani",position:"midfielder"},
			{number:"17",name:"G. Alanís",position:"midfielder"},
			{number:"11",name:"G. Núñez",position:"midfielder"},
			{number:"26",name:"Y. Arismendi",position:"forward"},
			{number:"32",name:"G. Mainero",position:"forward"},
			{number:"31",name:"B. Borasi",position:"forward"},
			{number:"9",name:"J. Torres",position:"forward"},
			{number:"19",name:"L. Gondou",position:"forward"},
			{number:"30",name:"P. Cucchi",position:"forward"},
			{number:"33",name:"R. Salinas",position:"forward"},

			]
		},
	 {
		teamName:"arsenal",
		players:[
			{number:"23",name:"A. Medina",position:"goalkeeper"},
			{number:"1",name:"D. Sappa",position:"goalkeeper"},
			{number:"12",name:"A. Rivero",position:"goalkeeper"},
			{number:"14",name:"G. Goñi",position:"defender"},
			{number:"6",name:"G. Suso",position:"defender"},
			{number:"33",name:"J. Bottinelli",position:"defender"},
			{number:"16",name:"I. Gariglio",position:"defender"},
			{number:"26",name:"L. Suárez",position:"defender"},
			{number:"3",name:"E. Papa",position:"defender"},
			{number:"29",name:"G. Benavídez",position:"defender"},
			{number:"18",name:"J. Navas",position:"defender"},
			{number:"4",name:"G. Mansilla",position:"midfielder"},
			{number:"8",name:"D. Miloc",position:"midfielder"},
			{number:"2",name:"J. Andrada",position:"midfielder"},
			{number:"5",name:"E. Méndez",position:"midfielder"},
			{number:"20",name:"V. Larralde",position:"midfielder"},
			{number:"24",name:"A. Antilef",position:"midfielder"},
			{number:"21",name:"L. Picco",position:"midfielder"},
			{number:"22",name:"J. Ortiz",position:"midfielder"},
			{number:"15",name:"R. Luna",position:"midfielder"},
			{number:"11",name:"N. Castro",position:"midfielder"},
			{number:"19",name:"B. Farioli",position:"midfielder"},
			{number:"10",name:"Ruiz",position:"midfielder"},
			{number:"25",name:"F. Kruspzky",position:"midfielder"},
			{number:"25",name:"M. Rogoski",position:"forward"},
			{number:"28",name:"M. Belloso",position:"forward"},
			{number:"9",name:"L. Albertengo",position:"forward"},
			{number:"17",name:"B. Sepúlveda",position:"forward"},
			{number:"20",name:"N. Mazzola",position:"forward"},
			{number:"7",name:"N. Miracco",position:"forward"},

			]
		},
]

export default teams
